//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaNet.Common.Security.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActionsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisaNet.Common.Security.Entities.Resources.ActionsStrings", typeof(ActionsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string AuditDetails {
            get {
                return ResourceManager.GetString("AuditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        public static string AuditList {
            get {
                return ResourceManager.GetString("AuditList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string BinGroupCreate {
            get {
                return ResourceManager.GetString("BinGroupCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string BinGroupDelete {
            get {
                return ResourceManager.GetString("BinGroupDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string BinGroupDetails {
            get {
                return ResourceManager.GetString("BinGroupDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string BinGroupEdit {
            get {
                return ResourceManager.GetString("BinGroupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        public static string BinGroupList {
            get {
                return ResourceManager.GetString("BinGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conciliación por día.
        /// </summary>
        public static string ConciliationDailyList {
            get {
                return ResourceManager.GetString("ConciliationDailyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutar Conciliación.
        /// </summary>
        public static string ConciliationVNP {
            get {
                return ResourceManager.GetString("ConciliationVNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string ContactCreate {
            get {
                return ResourceManager.GetString("ContactCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string ContactDelete {
            get {
                return ResourceManager.GetString("ContactDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ContactEdit {
            get {
                return ResourceManager.GetString("ContactEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        public static string ContactList {
            get {
                return ResourceManager.GetString("ContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string DiscountDetails {
            get {
                return ResourceManager.GetString("DiscountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string DiscountEdit {
            get {
                return ResourceManager.GetString("DiscountEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        public static string DiscountList {
            get {
                return ResourceManager.GetString("DiscountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string FaqCreate {
            get {
                return ResourceManager.GetString("FaqCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string FaqDelete {
            get {
                return ResourceManager.GetString("FaqDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string FaqDetails {
            get {
                return ResourceManager.GetString("FaqDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string FaqEdit {
            get {
                return ResourceManager.GetString("FaqEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        public static string FaqList {
            get {
                return ResourceManager.GetString("FaqList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string HomePageDetails {
            get {
                return ResourceManager.GetString("HomePageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string HomePageEdit {
            get {
                return ResourceManager.GetString("HomePageEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        public static string HomePageList {
            get {
                return ResourceManager.GetString("HomePageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string InstitutionalContentDetails {
            get {
                return ResourceManager.GetString("InstitutionalContentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string InstitutionalContentEdit {
            get {
                return ResourceManager.GetString("InstitutionalContentEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string LegalPagesDetails {
            get {
                return ResourceManager.GetString("LegalPagesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string LegalPagesEdit {
            get {
                return ResourceManager.GetString("LegalPagesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string NoticesDetails {
            get {
                return ResourceManager.GetString("NoticesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string NoticesEdit {
            get {
                return ResourceManager.GetString("NoticesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string ParametersDetails {
            get {
                return ResourceManager.GetString("ParametersDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ParametersEdit {
            get {
                return ResourceManager.GetString("ParametersEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string ReportsAutomaticPaymentsDetails {
            get {
                return ResourceManager.GetString("ReportsAutomaticPaymentsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string ReportsCardsDetails {
            get {
                return ResourceManager.GetString("ReportsCardsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string ReportsConciliationDetails {
            get {
                return ResourceManager.GetString("ReportsConciliationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corridas Conciliación.
        /// </summary>
        public static string ReportsConciliationRun {
            get {
                return ResourceManager.GetString("ReportsConciliationRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string ReportsCybersourceTransactionsDetails {
            get {
                return ResourceManager.GetString("ReportsCybersourceTransactionsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string ReportsDashboardDetails {
            get {
                return ResourceManager.GetString("ReportsDashboardDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        public static string ReportsDebitsSuscriptionList {
            get {
                return ResourceManager.GetString("ReportsDebitsSuscriptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carreteras Facturas.
        /// </summary>
        public static string ReportsHighwayBills {
            get {
                return ResourceManager.GetString("ReportsHighwayBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carretera Emails.
        /// </summary>
        public static string ReportsHighwayEmails {
            get {
                return ResourceManager.GetString("ReportsHighwayEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log integración.
        /// </summary>
        public static string ReportsIntegration {
            get {
                return ResourceManager.GetString("ReportsIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string ReportsServicesAssociatedDetails {
            get {
                return ResourceManager.GetString("ReportsServicesAssociatedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tc33.
        /// </summary>
        public static string ReportsTc33 {
            get {
                return ResourceManager.GetString("ReportsTc33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string ReportsTransactionsAmountDetails {
            get {
                return ResourceManager.GetString("ReportsTransactionsAmountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string ReportsTransactionsDetails {
            get {
                return ResourceManager.GetString("ReportsTransactionsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string ReportsUserCreate {
            get {
                return ResourceManager.GetString("ReportsUserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string ReportsUserDelete {
            get {
                return ResourceManager.GetString("ReportsUserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string ReportsUserDetails {
            get {
                return ResourceManager.GetString("ReportsUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ReportsUserEdit {
            get {
                return ResourceManager.GetString("ReportsUserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        public static string ReportsUserList {
            get {
                return ResourceManager.GetString("ReportsUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string ReportsVersionDetails {
            get {
                return ResourceManager.GetString("ReportsVersionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string RolesCreate {
            get {
                return ResourceManager.GetString("RolesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string RolesDelete {
            get {
                return ResourceManager.GetString("RolesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string RolesDetails {
            get {
                return ResourceManager.GetString("RolesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string RolesEdit {
            get {
                return ResourceManager.GetString("RolesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        public static string RolesList {
            get {
                return ResourceManager.GetString("RolesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string SubscriberCreate {
            get {
                return ResourceManager.GetString("SubscriberCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string SubscriberDelete {
            get {
                return ResourceManager.GetString("SubscriberDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string SubscriberDetails {
            get {
                return ResourceManager.GetString("SubscriberDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string SubscriberEdit {
            get {
                return ResourceManager.GetString("SubscriberEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        public static string SubscriberList {
            get {
                return ResourceManager.GetString("SubscriberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string SystemUsersCreate {
            get {
                return ResourceManager.GetString("SystemUsersCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string SystemUsersDelete {
            get {
                return ResourceManager.GetString("SystemUsersDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string SystemUsersDetails {
            get {
                return ResourceManager.GetString("SystemUsersDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string SystemUsersEdit {
            get {
                return ResourceManager.GetString("SystemUsersEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        public static string SystemUsersList {
            get {
                return ResourceManager.GetString("SystemUsersList", resourceCulture);
            }
        }
    }
}
