//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaNet.Common.Security.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FunctionalityStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FunctionalityStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisaNet.Common.Security.Entities.Resources.FunctionalityStrings", typeof(FunctionalityStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programa tarjetas.
        /// </summary>
        public static string AffiliationCard {
            get {
                return ResourceManager.GetString("AffiliationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoría.
        /// </summary>
        public static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoría de cambios.
        /// </summary>
        public static string AuditChangeLog {
            get {
                return ResourceManager.GetString("AuditChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bancos.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de BIN&apos;s.
        /// </summary>
        public static string BinGroup {
            get {
                return ResourceManager.GetString("BinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BINs.
        /// </summary>
        public static string Bins {
            get {
                return ResourceManager.GetString("Bins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conciliación diaria.
        /// </summary>
        public static string ConciliationDaily {
            get {
                return ResourceManager.GetString("ConciliationDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutar Conciliación.
        /// </summary>
        public static string ConciliationVNP {
            get {
                return ResourceManager.GetString("ConciliationVNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactos.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucursales.
        /// </summary>
        public static string CustomerSiteBranch {
            get {
                return ResourceManager.GetString("CustomerSiteBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercios.
        /// </summary>
        public static string CustomerSiteCommerce {
            get {
                return ResourceManager.GetString("CustomerSiteCommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios del sistema.
        /// </summary>
        public static string CustomerSiteSystemUser {
            get {
                return ResourceManager.GetString("CustomerSiteSystemUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercio de Débito.
        /// </summary>
        public static string DebitCommerce {
            get {
                return ResourceManager.GetString("DebitCommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuentos.
        /// </summary>
        public static string Discounts {
            get {
                return ResourceManager.GetString("Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas frecuentes.
        /// </summary>
        public static string Faqs {
            get {
                return ResourceManager.GetString("Faqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página de inicio.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenido institucional.
        /// </summary>
        public static string InstitutionalContent {
            get {
                return ResourceManager.GetString("InstitutionalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretes.
        /// </summary>
        public static string Interpreters {
            get {
                return ResourceManager.GetString("Interpreters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Páginas legales.
        /// </summary>
        public static string LegalPages {
            get {
                return ResourceManager.GetString("LegalPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novedades.
        /// </summary>
        public static string Notices {
            get {
                return ResourceManager.GetString("Notices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaciones.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promociones.
        /// </summary>
        public static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos programados.
        /// </summary>
        public static string ReportsAutomaticPayments {
            get {
                return ResourceManager.GetString("ReportsAutomaticPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjetas asociadas.
        /// </summary>
        public static string ReportsCards {
            get {
                return ResourceManager.GetString("ReportsCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conciliación resumen.
        /// </summary>
        public static string ReportsConciliation {
            get {
                return ResourceManager.GetString("ReportsConciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corridas Conciliación.
        /// </summary>
        public static string ReportsConciliationRun {
            get {
                return ResourceManager.GetString("ReportsConciliationRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacciones Cybersource.
        /// </summary>
        public static string ReportsCybersourceTransactions {
            get {
                return ResourceManager.GetString("ReportsCybersourceTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        public static string ReportsDashboard {
            get {
                return ResourceManager.GetString("ReportsDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitudes débito.
        /// </summary>
        public static string ReportsDebitsSuscription {
            get {
                return ResourceManager.GetString("ReportsDebitsSuscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carretera facturas.
        /// </summary>
        public static string ReportsHighwayBill {
            get {
                return ResourceManager.GetString("ReportsHighwayBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carretera emails.
        /// </summary>
        public static string ReportsHighwayEmail {
            get {
                return ResourceManager.GetString("ReportsHighwayEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integración externa.
        /// </summary>
        public static string ReportsIntegration {
            get {
                return ResourceManager.GetString("ReportsIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API LIF .
        /// </summary>
        public static string ReportsLifApiBill {
            get {
                return ResourceManager.GetString("ReportsLifApiBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correos electrónicos.
        /// </summary>
        public static string ReportsMails {
            get {
                return ResourceManager.GetString("ReportsMails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios asociados.
        /// </summary>
        public static string ReportsServicesAssociated {
            get {
                return ResourceManager.GetString("ReportsServicesAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tc33.
        /// </summary>
        public static string ReportsTc33 {
            get {
                return ResourceManager.GetString("ReportsTc33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacciones.
        /// </summary>
        public static string ReportsTransactions {
            get {
                return ResourceManager.GetString("ReportsTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de transacciones.
        /// </summary>
        public static string ReportsTransactionsAmount {
            get {
                return ResourceManager.GetString("ReportsTransactionsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios VNP.
        /// </summary>
        public static string ReportsUsers {
            get {
                return ResourceManager.GetString("ReportsUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versiones del sistema.
        /// </summary>
        public static string ReportsVersion {
            get {
                return ResourceManager.GetString("ReportsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios VON.
        /// </summary>
        public static string ReportsVonUsers {
            get {
                return ResourceManager.GetString("ReportsVonUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorías de servicios.
        /// </summary>
        public static string ServiceCategories {
            get {
                return ResourceManager.GetString("ServiceCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios contenedores.
        /// </summary>
        public static string ServiceContainers {
            get {
                return ResourceManager.GetString("ServiceContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suscriptores.
        /// </summary>
        public static string Subscribers {
            get {
                return ResourceManager.GetString("Subscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios del sistema.
        /// </summary>
        public static string SystemUsers {
            get {
                return ResourceManager.GetString("SystemUsers", resourceCulture);
            }
        }
    }
}
