//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaNet.Components.Sistarbanc.Implementations.WsConsultasLIF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://192.168.141.190/spfws/services/WsConsultasLIF", ConfigurationName="WsConsultasLIF.WsConsultasLIF")]
    public interface WsConsultasLIF {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FacturaDeConsultaLIF))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resultado))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getServicioImpagoLIFReturn")]
        VisaNet.Components.Sistarbanc.Implementations.WsConsultasLIF.ResultadoServicioImpagoLIF getServicioImpagoLIF(string banco, string idOrganismo, string tipoServicio, string[] idServicio, string firma);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getServicioImpagoLIFReturn")]
        System.Threading.Tasks.Task<VisaNet.Components.Sistarbanc.Implementations.WsConsultasLIF.ResultadoServicioImpagoLIF> getServicioImpagoLIFAsync(string banco, string idOrganismo, string tipoServicio, string[] idServicio, string firma);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WsConsultasLIF")]
    public partial class ResultadoServicioImpagoLIF : Resultado {
        
        private ServicioDeConsultaLIF servicioField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ServicioDeConsultaLIF servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
                this.RaisePropertyChanged("servicio");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WsConsultasLIF")]
    public partial class ServicioDeConsultaLIF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] descripcionField;
        
        private FacturaDeConsultaLIF[] facturasField;
        
        private string idOrganismoField;
        
        private string[] idServicioField;
        
        private string nombreClienteField;
        
        private string tipoServicioField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public FacturaDeConsultaLIF[] facturas {
            get {
                return this.facturasField;
            }
            set {
                this.facturasField = value;
                this.RaisePropertyChanged("facturas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string idOrganismo {
            get {
                return this.idOrganismoField;
            }
            set {
                this.idOrganismoField = value;
                this.RaisePropertyChanged("idOrganismo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] idServicio {
            get {
                return this.idServicioField;
            }
            set {
                this.idServicioField = value;
                this.RaisePropertyChanged("idServicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                this.nombreClienteField = value;
                this.RaisePropertyChanged("nombreCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tipoServicio {
            get {
                return this.tipoServicioField;
            }
            set {
                this.tipoServicioField = value;
                this.RaisePropertyChanged("tipoServicio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WsConsultasLIF")]
    public partial class FacturaDeConsultaLIF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool consumidorFinalField;
        
        private string[] descripcionField;
        
        private string facturaDGIField;
        
        private string fechaField;
        
        private string fechaEmisionField;
        
        private string fechaLimitePagoField;
        
        private string fechaVencimientoField;
        
        private string idFacturaField;
        
        private string idTransaccionField;
        
        private string importeFacturaField;
        
        private string importeGravadoField;
        
        private string monedaField;
        
        private int precedenciaField;
        
        private string tipoDocumentoField;
        
        /// <remarks/>
        public bool consumidorFinal {
            get {
                return this.consumidorFinalField;
            }
            set {
                this.consumidorFinalField = value;
                this.RaisePropertyChanged("consumidorFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string facturaDGI {
            get {
                return this.facturaDGIField;
            }
            set {
                this.facturaDGIField = value;
                this.RaisePropertyChanged("facturaDGI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fechaLimitePago {
            get {
                return this.fechaLimitePagoField;
            }
            set {
                this.fechaLimitePagoField = value;
                this.RaisePropertyChanged("fechaLimitePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("fechaVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string idFactura {
            get {
                return this.idFacturaField;
            }
            set {
                this.idFacturaField = value;
                this.RaisePropertyChanged("idFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string importeFactura {
            get {
                return this.importeFacturaField;
            }
            set {
                this.importeFacturaField = value;
                this.RaisePropertyChanged("importeFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string importeGravado {
            get {
                return this.importeGravadoField;
            }
            set {
                this.importeGravadoField = value;
                this.RaisePropertyChanged("importeGravado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("moneda");
            }
        }
        
        /// <remarks/>
        public int precedencia {
            get {
                return this.precedenciaField;
            }
            set {
                this.precedenciaField = value;
                this.RaisePropertyChanged("precedencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ResultadoServicioImpagoLIF))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WsConsultasLIF")]
    public partial class Resultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoErrorField;
        
        private string descripcionErrorField;
        
        /// <remarks/>
        public int codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("codigoError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("descripcionError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsConsultasLIFChannel : VisaNet.Components.Sistarbanc.Implementations.WsConsultasLIF.WsConsultasLIF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsConsultasLIFClient : System.ServiceModel.ClientBase<VisaNet.Components.Sistarbanc.Implementations.WsConsultasLIF.WsConsultasLIF>, VisaNet.Components.Sistarbanc.Implementations.WsConsultasLIF.WsConsultasLIF {
        
        public WsConsultasLIFClient() {
        }
        
        public WsConsultasLIFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsConsultasLIFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsConsultasLIFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsConsultasLIFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VisaNet.Components.Sistarbanc.Implementations.WsConsultasLIF.ResultadoServicioImpagoLIF getServicioImpagoLIF(string banco, string idOrganismo, string tipoServicio, string[] idServicio, string firma) {
            return base.Channel.getServicioImpagoLIF(banco, idOrganismo, tipoServicio, idServicio, firma);
        }
        
        public System.Threading.Tasks.Task<VisaNet.Components.Sistarbanc.Implementations.WsConsultasLIF.ResultadoServicioImpagoLIF> getServicioImpagoLIFAsync(string banco, string idOrganismo, string tipoServicio, string[] idServicio, string firma) {
            return base.Channel.getServicioImpagoLIFAsync(banco, idOrganismo, tipoServicio, idServicio, firma);
        }
    }
}
