//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaNet.Common.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisaNet.Common.Exceptions.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El link de acceso ha expirado..
        /// </summary>
        public static string ACCESS_TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("ACCESS_TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El link de acceso se encuentra inhabilitado..
        /// </summary>
        public static string ACCESS_TOKEN_INVALID_STATE {
            get {
                return ResourceManager.GetString("ACCESS_TOKEN_INVALID_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de programa repetido..
        /// </summary>
        public static string AFFILIATIONCARD_CODE_REPETED {
            get {
                return ResourceManager.GetString("AFFILIATIONCARD_CODE_REPETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cédula de identidad ingresada ya se encuentra registrada en el sistema..
        /// </summary>
        public static string ANONYMOUS_USER_CI_DUPLICATED {
            get {
                return ResourceManager.GetString("ANONYMOUS_USER_CI_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico ingresado ya se encuentra registrado en el sistema..
        /// </summary>
        public static string ANONYMOUS_USER_EMAIL_DUPLICATED {
            get {
                return ResourceManager.GetString("ANONYMOUS_USER_EMAIL_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faltan los datos del usuario anonimo..
        /// </summary>
        public static string ANONYMOUS_USER_MISSING {
            get {
                return ResourceManager.GetString("ANONYMOUS_USER_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no se encuentra habilitado..
        /// </summary>
        public static string APPLICATION_USER_DISABLED {
            get {
                return ResourceManager.GetString("APPLICATION_USER_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico ingresado ya se encuentra registrado en el sistema..
        /// </summary>
        public static string APPLICATION_USER_EMAIL_DUPLICATED {
            get {
                return ResourceManager.GetString("APPLICATION_USER_EMAIL_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de identidad ingresado ya se encuentra registrado en el sistema..
        /// </summary>
        public static string APPLICATION_USER_IDENTITY_DUPLICATED {
            get {
                return ResourceManager.GetString("APPLICATION_USER_IDENTITY_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de confirmación no válido..
        /// </summary>
        public static string APPLICATION_USER_INVALID_CONFIRMATION_TOKEN {
            get {
                return ResourceManager.GetString("APPLICATION_USER_INVALID_CONFIRMATION_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token inválido..
        /// </summary>
        public static string APPLICATION_USER_INVALID_TOKEN {
            get {
                return ResourceManager.GetString("APPLICATION_USER_INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador de Membership no encontrado..
        /// </summary>
        public static string APPLICATION_USER_MISSING_MEMBERSHIP_IDENTIFIER {
            get {
                return ResourceManager.GetString("APPLICATION_USER_MISSING_MEMBERSHIP_IDENTIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario indicado no existe..
        /// </summary>
        public static string APPLICATION_USER_NOT_EXIST {
            get {
                return ResourceManager.GetString("APPLICATION_USER_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail o contraseña anterior no coinciden..
        /// </summary>
        public static string APPLICATION_USER_OLD_PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("APPLICATION_USER_OLD_PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio no corresponde al usuario seleccionado.
        /// </summary>
        public static string APPLICATION_USER_SERVICEASSOCIATED {
            get {
                return ResourceManager.GetString("APPLICATION_USER_SERVICEASSOCIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El e-mail o la contraseña es incorrecto..
        /// </summary>
        public static string AUTH_LOGIN_ERROR {
            get {
                return ResourceManager.GetString("AUTH_LOGIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto ingresado debe ser mayor a 0..
        /// </summary>
        public static string AUTOMATIC_PAYMENT_AMOUNT_LESS_THAN_ONE {
            get {
                return ResourceManager.GetString("AUTOMATIC_PAYMENT_AMOUNT_LESS_THAN_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los días previos al vencimiento deben ser entre 1 y 5..
        /// </summary>
        public static string AUTOMATIC_PAYMENT_DAYS_WRONG {
            get {
                return ResourceManager.GetString("AUTOMATIC_PAYMENT_DAYS_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El banco BROU no puede ser eliminado. Se necesita para las transacciones de Sistarbanc.
        /// </summary>
        public static string BANK_BROU_MUSTEXISTS {
            get {
                return ResourceManager.GetString("BANK_BROU_MUSTEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código del banco ya existe..
        /// </summary>
        public static string BANK_CODE_USED {
            get {
                return ResourceManager.GetString("BANK_CODE_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El emisor no tiene configurado el pagos en cuota {0}..
        /// </summary>
        public static string BANK_DONOT_ALLOW_QUOTA {
            get {
                return ResourceManager.GetString("BANK_DONOT_ALLOW_QUOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar la cuota 1..
        /// </summary>
        public static string BANK_FIRST_QUOTA_NOT_SELECTED {
            get {
                return ResourceManager.GetString("BANK_FIRST_QUOTA_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del banco ya existe..
        /// </summary>
        public static string BANK_NAME_USED {
            get {
                return ResourceManager.GetString("BANK_NAME_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mínimo debe tener una cuota seleccionada..
        /// </summary>
        public static string BANK_QUOTA_EMPTY {
            get {
                return ResourceManager.GetString("BANK_QUOTA_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de comunicación Banred.
        /// </summary>
        public static string BANRED_COMMUNICATION {
            get {
                return ResourceManager.GetString("BANRED_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fault Banred.
        /// </summary>
        public static string BANRED_FAULT {
            get {
                return ResourceManager.GetString("BANRED_FAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la plataforma de Banred.
        /// </summary>
        public static string BANRED_GENERAL_ERROR {
            get {
                return ResourceManager.GetString("BANRED_GENERAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR EN BANRED.
        /// </summary>
        public static string BANRED_NORESPONSE {
            get {
                return ResourceManager.GetString("BANRED_NORESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error timeout Banred.
        /// </summary>
        public static string BANRED_TIMEOUT {
            get {
                return ResourceManager.GetString("BANRED_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de cuenta no encontrado..
        /// </summary>
        public static string BILL_ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("BILL_ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La factura se encuentra paga..
        /// </summary>
        public static string BILL_ALREADY_PAID {
            get {
                return ResourceManager.GetString("BILL_ALREADY_PAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe la cuenta. Por favor validá el número de cuenta ingresado..
        /// </summary>
        public static string BILL_ANTEL_ACCOUNTNOTFOUND {
            get {
                return ResourceManager.GetString("BILL_ANTEL_ACCOUNTNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe la cuenta. Ingresá el número de cuenta (SIN guiones) que aparece en su factura (Ej: 95299766000145)..
        /// </summary>
        public static string BILL_ANTEL_ONLYNUMBER {
            get {
                return ResourceManager.GetString("BILL_ANTEL_ONLYNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura vencida..
        /// </summary>
        public static string BILL_EXPIRED {
            get {
                return ResourceManager.GetString("BILL_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No posee deuda..
        /// </summary>
        public static string BILL_GEOCOM_004 {
            get {
                return ResourceManager.GetString("BILL_GEOCOM_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo realizar el pago ya que esta factura no se puede paga por internet..
        /// </summary>
        public static string BILL_NOT_PAYABLE {
            get {
                return ResourceManager.GetString("BILL_NOT_PAYABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe la cuenta. Por favor validá el número de cuenta ingresado..
        /// </summary>
        public static string BILL_OSE_ACCOUNTNOTFOUND {
            get {
                return ResourceManager.GetString("BILL_OSE_ACCOUNTNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio no se encuentra disponible. Intentá nuevamente o espera unos minutos..
        /// </summary>
        public static string BILL_SERVICE_DISABLE {
            get {
                return ResourceManager.GetString("BILL_SERVICE_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto de la factura debe ser mayor a 0. Id operacion &apos;{0}&apos;, Monto &apos;{1}&apos;.
        /// </summary>
        public static string BILL_TAXED_AMOUNT_NOT_ALLOW {
            get {
                return ResourceManager.GetString("BILL_TAXED_AMOUNT_NOT_ALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe la cuenta. Por favor validá el número de cliente ingresado..
        /// </summary>
        public static string BILL_TCC_ACCOUNTNOTFOUND {
            get {
                return ResourceManager.GetString("BILL_TCC_ACCOUNTNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe la cuenta. Por favor validá el número de cuenta ingresado..
        /// </summary>
        public static string BILL_UTE_ACCOUNTNOTFOUND {
            get {
                return ResourceManager.GetString("BILL_UTE_ACCOUNTNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El banco asociado al bin es distinto al banco asociado al programa..
        /// </summary>
        public static string BIN_BANKID_AFFILIATIONCARD_BANKID {
            get {
                return ResourceManager.GetString("BIN_BANKID_AFFILIATIONCARD_BANKID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dado el tipo de tarjeta seleccionado, el país debe ser UY.
        /// </summary>
        public static string BIN_COUNTRY_MUST_BE_UY {
            get {
                return ResourceManager.GetString("BIN_COUNTRY_MUST_BE_UY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dado el tipo de tarjeta seleccionado, el país no puede ser UY.
        /// </summary>
        public static string BIN_COUNTRY_MUST_NOT_BE_UY {
            get {
                return ResourceManager.GetString("BIN_COUNTRY_MUST_NOT_BE_UY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio {0} ({1}) seleccionado no se puede pagar con este tipo de tarjeta, bin {2}.
        /// </summary>
        public static string BIN_ERROR_NOSERVICE {
            get {
                return ResourceManager.GetString("BIN_ERROR_NOSERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio {0} ({1}) seleccionado no se puede pagar con este tipo de tarjeta, bin {2} INACTIVO.
        /// </summary>
        public static string BIN_ERROR_NOTACTIVE {
            get {
                return ResourceManager.GetString("BIN_ERROR_NOTACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El sistema no reconoce la tarjeta ingresada. Bin {0}.
        /// </summary>
        public static string BIN_ERROR_VALUE_NOT_RECOGNIZED {
            get {
                return ResourceManager.GetString("BIN_ERROR_VALUE_NOT_RECOGNIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta tarjeta no está habilitada para este servicio..
        /// </summary>
        public static string BIN_NOTACTIVE {
            get {
                return ResourceManager.GetString("BIN_NOTACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El BIN no está activo..
        /// </summary>
        public static string BIN_NOTACTIVE2 {
            get {
                return ResourceManager.GetString("BIN_NOTACTIVE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo realizar la migración porque la nueva tarjeta no es aceptada por alguno de los servicios. Pruebe migrar los servicios de forma individual..
        /// </summary>
        public static string BIN_NOTVALID_FOR_ALL {
            get {
                return ResourceManager.GetString("BIN_NOTVALID_FOR_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjeta no habilitada para este servicio. Por favor intentá con otra tarjeta..
        /// </summary>
        public static string BIN_NOTVALID_FOR_SERVICE {
            get {
                return ResourceManager.GetString("BIN_NOTVALID_FOR_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio seleccionado no se puede pagar con este tipo de tarjeta..
        /// </summary>
        public static string BIN_VALUE_FOR_SERVICE_NOT_VALID {
            get {
                return ResourceManager.GetString("BIN_VALUE_FOR_SERVICE_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El sistema no reconoce la tarjeta ingresada. Por favor intentá con otra..
        /// </summary>
        public static string BIN_VALUE_NOT_RECOGNIZED {
            get {
                return ResourceManager.GetString("BIN_VALUE_NOT_RECOGNIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor de BIN ya existente..
        /// </summary>
        public static string BIN_VALUE_USED {
            get {
                return ResourceManager.GetString("BIN_VALUE_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El grupo de bin &apos;{0}&apos; no puede ser eliminado ya que es default.
        /// </summary>
        public static string BINGROUP_DEFAULT_CANNOT_BE_DELETED {
            get {
                return ResourceManager.GetString("BINGROUP_DEFAULT_CANNOT_BE_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del grupo de bin &apos;{0}&apos; no puede ser editado ya que es default.
        /// </summary>
        public static string BINGROUP_DEFAULT_CANNOT_BE_RENAMED {
            get {
                return ResourceManager.GetString("BINGROUP_DEFAULT_CANNOT_BE_RENAMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del grupo duplicado..
        /// </summary>
        public static string BINGROUP_NAME_USED {
            get {
                return ResourceManager.GetString("BINGROUP_NAME_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tarjeta no se puede eliminar porque es la unica que tiene el servicio asociado..
        /// </summary>
        public static string CARD_DELETE_ERROR_SERVICEASSOCIATED_WITHOUT_CARD {
            get {
                return ResourceManager.GetString("CARD_DELETE_ERROR_SERVICEASSOCIATED_WITHOUT_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tarjeta está vencida.
        /// </summary>
        public static string CARD_EXPIRED {
            get {
                return ResourceManager.GetString("CARD_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de tarjeta ingresada no permite pago en cuotas..
        /// </summary>
        public static string CARDTYPE_NOT_ALLOWED_QUOTA_PAYMENT {
            get {
                return ResourceManager.GetString("CARDTYPE_NOT_ALLOWED_QUOTA_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de tarjeta inválido.
        /// </summary>
        public static string CARDTYPE_NOT_DEFINED {
            get {
                return ResourceManager.GetString("CARDTYPE_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La conexión hacia el servidor de archivos falló. Intente mas tarde..
        /// </summary>
        public static string CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clave de acceso en cybersource no puede ser vacía..
        /// </summary>
        public static string CYBERSOURCE_ACCESS_KEY {
            get {
                return ResourceManager.GetString("CYBERSOURCE_ACCESS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de comunicación.
        /// </summary>
        public static string CYBERSOURCE_COMMUNICATION {
            get {
                return ResourceManager.GetString("CYBERSOURCE_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de fault.
        /// </summary>
        public static string CYBERSOURCE_FAULT {
            get {
                return ResourceManager.GetString("CYBERSOURCE_FAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en metodo refund payment.
        /// </summary>
        public static string CYBERSOURCE_REFUND_ERROR {
            get {
                return ResourceManager.GetString("CYBERSOURCE_REFUND_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clave de seguridad en cybersource no puede ser vacía..
        /// </summary>
        public static string CYBERSOURCE_SECRET_KEY {
            get {
                return ResourceManager.GetString("CYBERSOURCE_SECRET_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de timeout.
        /// </summary>
        public static string CYBERSOURCE_TIMEOUT {
            get {
                return ResourceManager.GetString("CYBERSOURCE_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en método void payment.
        /// </summary>
        public static string CYBERSOURCE_VOID_ERROR {
            get {
                return ResourceManager.GetString("CYBERSOURCE_VOID_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El bin por defecto no puede ser eliminado.
        /// </summary>
        public static string DEFAULT_BIN_CANNOT_BE_DELETED {
            get {
                return ResourceManager.GetString("DEFAULT_BIN_CANNOT_BE_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El bin por defecto no puede ser editado.
        /// </summary>
        public static string DEFAULT_BIN_CANNOT_BE_EDITED {
            get {
                return ResourceManager.GetString("DEFAULT_BIN_CANNOT_BE_EDITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El indicador de Ley enviado es inválido..
        /// </summary>
        public static string DISCOUNT_INVALID_LAW_ID {
            get {
                return ResourceManager.GetString("DISCOUNT_INVALID_LAW_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El modelo enviado es inválido.
        /// </summary>
        public static string DISCOUNT_INVALID_MODEL {
            get {
                return ResourceManager.GetString("DISCOUNT_INVALID_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay configurado más de un descuento para el tipo de tarjeta y fecha ingresada. Fecha: {0}.
        /// </summary>
        public static string DISCOUNT_MULTIPLE_DISCOUNT_FOR_CARDTYPE {
            get {
                return ResourceManager.GetString("DISCOUNT_MULTIPLE_DISCOUNT_FOR_CARDTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra configurado el descuento para el tipo de tarjeta y fecha ingresada. Fecha: {0} Tarjeta: {1}.
        /// </summary>
        public static string DISCOUNT_NO_DISCOUNT_FOR_CARDTYPE__INTERNAL {
            get {
                return ResourceManager.GetString("DISCOUNT_NO_DISCOUNT_FOR_CARDTYPE__INTERNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo pueden cancelarse emails con estado: &quot;Error al enviar a Mailgun&quot; y &quot;Fallo de envío (recuperable)&quot;.
        /// </summary>
        public static string EMAIL_STATUS_CANNOT_BE_CANCELED {
            get {
                return ResourceManager.GetString("EMAIL_STATUS_CANNOT_BE_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta ya existente..
        /// </summary>
        public static string FAQ_QUESTION_ALREADY_USED {
            get {
                return ResourceManager.GetString("FAQ_QUESTION_ALREADY_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudieron obtener las facturas por problemas en la comunicación con el comercio..
        /// </summary>
        public static string GENERAL_COMUNICATION_ERROR_BILL {
            get {
                return ResourceManager.GetString("GENERAL_COMUNICATION_ERROR_BILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo pagar la factura por problemas en la comunicación con el comercio..
        /// </summary>
        public static string GENERAL_COMUNICATION_ERROR_PAYMENT {
            get {
                return ResourceManager.GetString("GENERAL_COMUNICATION_ERROR_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error. Intentá nuevamente en unos minutos..
        /// </summary>
        public static string GENERAL_ERROR {
            get {
                return ResourceManager.GetString("GENERAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener factura. .
        /// </summary>
        public static string GEOCOM_CANTGETBILL {
            get {
                return ResourceManager.GetString("GEOCOM_CANTGETBILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error en Geocom al confirmar un pago..
        /// </summary>
        public static string GEOCOM_CONFIRMATION_ERROR {
            get {
                return ResourceManager.GetString("GEOCOM_CONFIRMATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se obtuvieron dos id padron para un paquete de datos..
        /// </summary>
        public static string GEOCOM_MULTIPLEIDPADRON {
            get {
                return ResourceManager.GetString("GEOCOM_MULTIPLEIDPADRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay respuesta de Geocom.
        /// </summary>
        public static string GEOCOM_NORESPONSE {
            get {
                return ResourceManager.GetString("GEOCOM_NORESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró un objecto con ese identificador..
        /// </summary>
        public static string ID_NOT_FOUND {
            get {
                return ResourceManager.GetString("ID_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de interprete ya existente..
        /// </summary>
        public static string INTERPRETER_NAME_USED {
            get {
                return ResourceManager.GetString("INTERPRETER_NAME_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tarjeta asociada no pertenece al usaurio..
        /// </summary>
        public static string INVALID_CARD_ASOCIATION {
            get {
                return ResourceManager.GetString("INVALID_CARD_ASOCIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de imagen inválido..
        /// </summary>
        public static string INVALID_IMAGE_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_IMAGE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo agregar el mail en mailgun..
        /// </summary>
        public static string MAILGUN_ADD_ERROR {
            get {
                return ResourceManager.GetString("MAILGUN_ADD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puedo eliminar el mail en mailgun..
        /// </summary>
        public static string MAILGUN_DELETE_ERROR {
            get {
                return ResourceManager.GetString("MAILGUN_DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el email en la base de datos MailgunId: {0}.
        /// </summary>
        public static string MAILGUN_EMAILNOTFOUND {
            get {
                return ResourceManager.GetString("MAILGUN_EMAILNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id de operación repetido..
        /// </summary>
        public static string OPERATION_ID_REPETED {
            get {
                return ResourceManager.GetString("OPERATION_ID_REPETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de tarjeta no es válido..
        /// </summary>
        public static string PAYMENT_CARD_INVALID {
            get {
                return ResourceManager.GetString("PAYMENT_CARD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago no realizado. El campo 48 no se pudo validar..
        /// </summary>
        public static string PAYMENT_FIELD48_WRONG {
            get {
                return ResourceManager.GetString("PAYMENT_FIELD48_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacción sin factura asociada..
        /// </summary>
        public static string PAYMENT_NO_BILL {
            get {
                return ResourceManager.GetString("PAYMENT_NO_BILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El pago indicado no existe..
        /// </summary>
        public static string PAYMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PAYMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El pago ({0}) indicado no existe..
        /// </summary>
        public static string PAYMENT_NOT_FOUND_NROTRNS {
            get {
                return ResourceManager.GetString("PAYMENT_NOT_FOUND_NROTRNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El pago ({0}) se encuentra en estado {1}..
        /// </summary>
        public static string PAYMENT_STATUS_NOT_VALID {
            get {
                return ResourceManager.GetString("PAYMENT_STATUS_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La transacción y el usuario no estan relacionados..
        /// </summary>
        public static string PAYMENT_USER_NOT_RELATED {
            get {
                return ResourceManager.GetString("PAYMENT_USER_NOT_RELATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra configurada la cotización para la UI para la fecha {0}.
        /// </summary>
        public static string QUOTATION_NO_CONFIGURED_FOR_UI__INTERNAL {
            get {
                return ResourceManager.GetString("QUOTATION_NO_CONFIGURED_FOR_UI__INTERNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen usuarios asociados al rol indicado..
        /// </summary>
        public static string ROLE_USERS_ASSOCIATED {
            get {
                return ResourceManager.GetString("ROLE_USERS_ASSOCIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El appId ingresado ya está en uso para otro servicio..
        /// </summary>
        public static string SERVICE_APPID_DUPLICATED {
            get {
                return ResourceManager.GetString("SERVICE_APPID_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio esta asociado a un usuario, no se puede eliminar..
        /// </summary>
        public static string SERVICE_ASOCIATED {
            get {
                return ResourceManager.GetString("SERVICE_ASOCIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código del servicio en Banred/Sistarbanc ya fue utilizado..
        /// </summary>
        public static string SERVICE_BANRED_SISTARBANC_CODE_UNIQUE {
            get {
                return ResourceManager.GetString("SERVICE_BANRED_SISTARBANC_CODE_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Servicio debe tener al menos un grupo de BIN&apos;s.
        /// </summary>
        public static string SERVICE_BINGROUP_REQUIRED {
            get {
                return ResourceManager.GetString("SERVICE_BINGROUP_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar una tarjeta que ha realizado pagos..
        /// </summary>
        public static string SERVICE_CARD_HAS_PAYMENTS {
            get {
                return ResourceManager.GetString("SERVICE_CARD_HAS_PAYMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede desactivar una tarjeta configurada para el pago de un servicio..
        /// </summary>
        public static string SERVICE_CARD_IS_DEFAULT {
            get {
                return ResourceManager.GetString("SERVICE_CARD_IS_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede desactivar una tarjeta configurada para el pago de un servicio. Primero debes migrar los servicios a otra tarjeta..
        /// </summary>
        public static string SERVICE_CARD_IS_DEFAULT_MIGRATE_SERVICES {
            get {
                return ResourceManager.GetString("SERVICE_CARD_IS_DEFAULT_MIGRATE_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede desactivar la tarjeta ya que es utilizada en el pago de un débito. Primero debes migrar los débitos a otra tarjeta..
        /// </summary>
        public static string SERVICE_CARD_IS_USED_MIGRATE_DEBITS {
            get {
                return ResourceManager.GetString("SERVICE_CARD_IS_USED_MIGRATE_DEBITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede desactivar una tarjeta configurada para el pago de un servicio. Primero debes migrar los servicios a otra tarjeta..
        /// </summary>
        public static string SERVICE_CARD_IS_USED_MIGRATE_SERVICES {
            get {
                return ResourceManager.GetString("SERVICE_CARD_IS_USED_MIGRATE_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código del servicio en Cybersource ya fue utilizado..
        /// </summary>
        public static string SERVICE_CYBERSOURCE_CODE_UNIQUE {
            get {
                return ResourceManager.GetString("SERVICE_CYBERSOURCE_CODE_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio que querés activar no tiene una tarjeta por defecto activa. Por favor, ingresá una nueva tarjeta o activá una..
        /// </summary>
        public static string SERVICE_DEFAULT_CARD_NOTACTIVE {
            get {
                return ResourceManager.GetString("SERVICE_DEFAULT_CARD_NOTACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio que querés guardar no puede ser contenido por otro, ya que es un servicio padre..
        /// </summary>
        public static string SERVICE_IS_CONTAINER {
            get {
                return ResourceManager.GetString("SERVICE_IS_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El merchantId ingresado ya está en uso para otro servicio con la pasarela apps seleccionada.
        /// </summary>
        public static string SERVICE_MERCHANTID_DUPLICATED {
            get {
                return ResourceManager.GetString("SERVICE_MERCHANTID_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio {0} se encuentra momentaneamente fuera de servicio hasta el {1}..
        /// </summary>
        public static string SERVICE_MOMENTARILY_DISABLED {
            get {
                return ResourceManager.GetString("SERVICE_MOMENTARILY_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de servicio ya existente..
        /// </summary>
        public static string SERVICE_NAME_ALREADY_USED {
            get {
                return ResourceManager.GetString("SERVICE_NAME_ALREADY_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio {0} no tiene configurado el pagos en cuota..
        /// </summary>
        public static string SERVICE_NOT_ALLOWED_QUOTA_PAYMENT {
            get {
                return ResourceManager.GetString("SERVICE_NOT_ALLOWED_QUOTA_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio seleccionado no pudo ser eliminado..
        /// </summary>
        public static string SERVICE_NOT_DELETED {
            get {
                return ResourceManager.GetString("SERVICE_NOT_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio indicado no existe..
        /// </summary>
        public static string SERVICE_NOT_EXIST {
            get {
                return ResourceManager.GetString("SERVICE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen pagos asociados al servicio indicado..
        /// </summary>
        public static string SERVICE_PAYMENTS_ASSOCIATED {
            get {
                return ResourceManager.GetString("SERVICE_PAYMENTS_ASSOCIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio (o su servicio contenedor) pide referencias pero no se definieron las mismas..
        /// </summary>
        public static string SERVICE_REFERENCES_EMPTY {
            get {
                return ResourceManager.GetString("SERVICE_REFERENCES_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar la categoría seleccionada, hay un servicio que la utiliza..
        /// </summary>
        public static string SERVICECATEGORY_IN_SERVICE {
            get {
                return ResourceManager.GetString("SERVICECATEGORY_IN_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la categoría ya existente..
        /// </summary>
        public static string SERVICECATEGORY_NAME_ALREADY_USED {
            get {
                return ResourceManager.GetString("SERVICECATEGORY_NAME_ALREADY_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay respuesta de Sistarbanc.
        /// </summary>
        public static string SISTARBANC_NORESPONSE {
            get {
                return ResourceManager.GetString("SISTARBANC_NORESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo realizar el pago ya que esta factura se encuentra paga..
        /// </summary>
        public static string SISTARBANC_NROERROR_29 {
            get {
                return ResourceManager.GetString("SISTARBANC_NROERROR_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio no se encuentra disponible para recibir pagos, comunicate con nuestro Call Center.
        /// </summary>
        public static string SISTARBANC_NROERROR_50 {
            get {
                return ResourceManager.GetString("SISTARBANC_NROERROR_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo realizar el pago ya que existe una factura previa impaga..
        /// </summary>
        public static string SISTARBANC_NROERROR_57 {
            get {
                return ResourceManager.GetString("SISTARBANC_NROERROR_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección de correo ya existente..
        /// </summary>
        public static string SUBSCRIBER_EMAIL_ALREADY_USED {
            get {
                return ResourceManager.GetString("SUBSCRIBER_EMAIL_ALREADY_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error en Sucive al confirmar un pago..
        /// </summary>
        public static string SUCIVE_CONFIRMATION_ERROR {
            get {
                return ResourceManager.GetString("SUCIVE_CONFIRMATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe tramite para el valor ingresado..
        /// </summary>
        public static string SUCIVE_ERROR090 {
            get {
                return ResourceManager.GetString("SUCIVE_ERROR090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se obtuvieron dos id padron para un paquete de datos..
        /// </summary>
        public static string SUCIVE_MULTIPLEIDPADRON {
            get {
                return ResourceManager.GetString("SUCIVE_MULTIPLEIDPADRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay respuesta de SUCIVE.
        /// </summary>
        public static string SUCIVE_NORESPONSE {
            get {
                return ResourceManager.GetString("SUCIVE_NORESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no se encuentra habilitado..
        /// </summary>
        public static string SYSTEM_USER_DISABLED {
            get {
                return ResourceManager.GetString("SYSTEM_USER_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario indicado no existe..
        /// </summary>
        public static string SYSTEM_USER_NOT_EXIST {
            get {
                return ResourceManager.GetString("SYSTEM_USER_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ya existente..
        /// </summary>
        public static string SYSTEM_USER_USERNAME_DUPLICATED {
            get {
                return ResourceManager.GetString("SYSTEM_USER_USERNAME_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró archivo Tc33.
        /// </summary>
        public static string TC33_NOT_FOUND {
            get {
                return ResourceManager.GetString("TC33_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tarjeta no corresponde al usuario seleccionado..
        /// </summary>
        public static string USER_CARD_NOT_MATCH {
            get {
                return ResourceManager.GetString("USER_CARD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección de correo ya existente..
        /// </summary>
        public static string USER_EMAIL_DUPLICATED {
            get {
                return ResourceManager.GetString("USER_EMAIL_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falta la dirección de correo electrónico.
        /// </summary>
        public static string USER_EMAIL_MISSING {
            get {
                return ResourceManager.GetString("USER_EMAIL_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falta el número de teléfono .
        /// </summary>
        public static string USER_MOBILEPHONE_MISSING {
            get {
                return ResourceManager.GetString("USER_MOBILEPHONE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario indicado no existe..
        /// </summary>
        public static string USER_NOT_EXIST {
            get {
                return ResourceManager.GetString("USER_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ya existente..
        /// </summary>
        public static string USER_USERNAME_DUPLICATED {
            get {
                return ResourceManager.GetString("USER_USERNAME_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario y dirección de correo no coninciden..
        /// </summary>
        public static string USER_USERNAME_EMAIL_NOT_MATCH {
            get {
                return ResourceManager.GetString("USER_USERNAME_EMAIL_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El link de acceso ha expirado..
        /// </summary>
        public static string WEBBHOOKREGISTRATION_ACCESSTOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("WEBBHOOKREGISTRATION_ACCESSTOKEN_EXPIRED", resourceCulture);
            }
        }
    }
}
