//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaNet.Banred.Mock.WcfBanredTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.banred.com.uy/PagosBancos/", ConfigurationName="WcfBanredTest.PagosBancos")]
    public interface PagosBancos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banred.com.uy/PagosBancos/consultaEntesDisponibles", ReplyAction="*")]
        VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesResponse consultaEntesDisponibles(VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banred.com.uy/PagosBancos/consultaEntesDisponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesResponse> consultaEntesDisponiblesAsync(VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banred.com.uy/PagosBancos/consultaFacturasEnte", ReplyAction="*")]
        VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteResponse consultaFacturasEnte(VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banred.com.uy/PagosBancos/consultaFacturasEnte", ReplyAction="*")]
        System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteResponse> consultaFacturasEnteAsync(VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banred.com.uy/PagosBancos/pagarFacturaEnte", ReplyAction="*")]
        VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteResponse pagarFacturaEnte(VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banred.com.uy/PagosBancos/pagarFacturaEnte", ReplyAction="*")]
        System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteResponse> pagarFacturaEnteAsync(VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banred.com.uy/PagosBancos/confirmarOperacion", ReplyAction="*")]
        VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionResponse confirmarOperacion(VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banred.com.uy/PagosBancos/confirmarOperacion", ReplyAction="*")]
        System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionResponse> confirmarOperacionAsync(VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banred.com.uy/PagosBancos/consultaEstadoOperacion", ReplyAction="*")]
        VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionResponse consultaEstadoOperacion(VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banred.com.uy/PagosBancos/consultaEstadoOperacion", ReplyAction="*")]
        System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionResponse> consultaEstadoOperacionAsync(VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banred.com.uy/PagosBancos/consultaEstadoPago", ReplyAction="*")]
        VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoResponse consultaEstadoPago(VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banred.com.uy/PagosBancos/consultaEstadoPago", ReplyAction="*")]
        System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoResponse> consultaEstadoPagoAsync(VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banred.com.uy/PagosBancos/resetearEpin", ReplyAction="*")]
        VisaNet.Banred.Mock.WcfBanredTest.resetearEpinResponse resetearEpin(VisaNet.Banred.Mock.WcfBanredTest.resetearEpinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banred.com.uy/PagosBancos/resetearEpin", ReplyAction="*")]
        System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.resetearEpinResponse> resetearEpinAsync(VisaNet.Banred.Mock.WcfBanredTest.resetearEpinRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaEntesDisponiblesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaEntesDisponibles", Namespace="http://www.banred.com.uy/PagosBancos/", Order=0)]
        public VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesRequestBody Body;
        
        public consultaEntesDisponiblesRequest() {
        }
        
        public consultaEntesDisponiblesRequest(VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultaEntesDisponiblesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idAgenteExterno;
        
        public consultaEntesDisponiblesRequestBody() {
        }
        
        public consultaEntesDisponiblesRequestBody(string idAgenteExterno) {
            this.idAgenteExterno = idAgenteExterno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaEntesDisponiblesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaEntesDisponiblesResponse", Namespace="http://www.banred.com.uy/PagosBancos/", Order=0)]
        public VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesResponseBody Body;
        
        public consultaEntesDisponiblesResponse() {
        }
        
        public consultaEntesDisponiblesResponse(VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultaEntesDisponiblesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int resultado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string textoResultado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string listaEntes;
        
        public consultaEntesDisponiblesResponseBody() {
        }
        
        public consultaEntesDisponiblesResponseBody(int resultado, string textoResultado, string listaEntes) {
            this.resultado = resultado;
            this.textoResultado = textoResultado;
            this.listaEntes = listaEntes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaFacturasEnteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaFacturasEnte", Namespace="http://www.banred.com.uy/PagosBancos/", Order=0)]
        public VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteRequestBody Body;
        
        public consultaFacturasEnteRequest() {
        }
        
        public consultaFacturasEnteRequest(VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultaFacturasEnteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idAgenteExterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string codigoEnte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string codigoCuentaEnte;
        
        public consultaFacturasEnteRequestBody() {
        }
        
        public consultaFacturasEnteRequestBody(string idAgenteExterno, string codigoEnte, string codigoCuentaEnte) {
            this.idAgenteExterno = idAgenteExterno;
            this.codigoEnte = codigoEnte;
            this.codigoCuentaEnte = codigoCuentaEnte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaFacturasEnteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaFacturasEnteResponse", Namespace="http://www.banred.com.uy/PagosBancos/", Order=0)]
        public VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteResponseBody Body;
        
        public consultaFacturasEnteResponse() {
        }
        
        public consultaFacturasEnteResponse(VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultaFacturasEnteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int resultado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string textoResultado;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cantFacturas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string listaFacturas;
        
        public consultaFacturasEnteResponseBody() {
        }
        
        public consultaFacturasEnteResponseBody(int resultado, string textoResultado, int cantFacturas, string listaFacturas) {
            this.resultado = resultado;
            this.textoResultado = textoResultado;
            this.cantFacturas = cantFacturas;
            this.listaFacturas = listaFacturas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pagarFacturaEnteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pagarFacturaEnte", Namespace="http://www.banred.com.uy/PagosBancos/", Order=0)]
        public VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteRequestBody Body;
        
        public pagarFacturaEnteRequest() {
        }
        
        public pagarFacturaEnteRequest(VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class pagarFacturaEnteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idAgenteExterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string codigoEnte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string codigoCuentaEnte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nroFactura;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string montoPago;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MontoDescuentoIVA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string monedaPago;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fechaVencimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string idOperacionAgente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string firmaDigital;
        
        public pagarFacturaEnteRequestBody() {
        }
        
        public pagarFacturaEnteRequestBody(string idAgenteExterno, string codigoEnte, string codigoCuentaEnte, string nroFactura, string montoPago, string MontoDescuentoIVA, string monedaPago, string fechaVencimiento, string idOperacionAgente, string firmaDigital) {
            this.idAgenteExterno = idAgenteExterno;
            this.codigoEnte = codigoEnte;
            this.codigoCuentaEnte = codigoCuentaEnte;
            this.nroFactura = nroFactura;
            this.montoPago = montoPago;
            this.MontoDescuentoIVA = MontoDescuentoIVA;
            this.monedaPago = monedaPago;
            this.fechaVencimiento = fechaVencimiento;
            this.idOperacionAgente = idOperacionAgente;
            this.firmaDigital = firmaDigital;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pagarFacturaEnteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pagarFacturaEnteResponse", Namespace="http://www.banred.com.uy/PagosBancos/", Order=0)]
        public VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteResponseBody Body;
        
        public pagarFacturaEnteResponse() {
        }
        
        public pagarFacturaEnteResponse(VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class pagarFacturaEnteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int resultado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string textoResultado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nroTransaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fechaHoraPago;
        
        public pagarFacturaEnteResponseBody() {
        }
        
        public pagarFacturaEnteResponseBody(int resultado, string textoResultado, string nroTransaccion, string fechaHoraPago) {
            this.resultado = resultado;
            this.textoResultado = textoResultado;
            this.nroTransaccion = nroTransaccion;
            this.fechaHoraPago = fechaHoraPago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class confirmarOperacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="confirmarOperacion", Namespace="http://www.banred.com.uy/PagosBancos/", Order=0)]
        public VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionRequestBody Body;
        
        public confirmarOperacionRequest() {
        }
        
        public confirmarOperacionRequest(VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class confirmarOperacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idAgenteExterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idOperacionExterna;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string idOperacionAgente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string firmaDigital;
        
        public confirmarOperacionRequestBody() {
        }
        
        public confirmarOperacionRequestBody(string idAgenteExterno, string idOperacionExterna, string status, string idOperacionAgente, string firmaDigital) {
            this.idAgenteExterno = idAgenteExterno;
            this.idOperacionExterna = idOperacionExterna;
            this.status = status;
            this.idOperacionAgente = idOperacionAgente;
            this.firmaDigital = firmaDigital;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class confirmarOperacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="confirmarOperacionResponse", Namespace="http://www.banred.com.uy/PagosBancos/", Order=0)]
        public VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionResponseBody Body;
        
        public confirmarOperacionResponse() {
        }
        
        public confirmarOperacionResponse(VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class confirmarOperacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int resultado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string textoResultado;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nroTransaccionExterna;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fechaHoraConfirmacion;
        
        public confirmarOperacionResponseBody() {
        }
        
        public confirmarOperacionResponseBody(int resultado, string textoResultado, int nroTransaccionExterna, string fechaHoraConfirmacion) {
            this.resultado = resultado;
            this.textoResultado = textoResultado;
            this.nroTransaccionExterna = nroTransaccionExterna;
            this.fechaHoraConfirmacion = fechaHoraConfirmacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaEstadoOperacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaEstadoOperacion", Namespace="http://www.banred.com.uy/PagosBancos/", Order=0)]
        public VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionRequestBody Body;
        
        public consultaEstadoOperacionRequest() {
        }
        
        public consultaEstadoOperacionRequest(VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultaEstadoOperacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idAgenteExterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idOperacionExterna;
        
        public consultaEstadoOperacionRequestBody() {
        }
        
        public consultaEstadoOperacionRequestBody(string idAgenteExterno, string idOperacionExterna) {
            this.idAgenteExterno = idAgenteExterno;
            this.idOperacionExterna = idOperacionExterna;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaEstadoOperacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaEstadoOperacionResponse", Namespace="http://www.banred.com.uy/PagosBancos/", Order=0)]
        public VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionResponseBody Body;
        
        public consultaEstadoOperacionResponse() {
        }
        
        public consultaEstadoOperacionResponse(VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultaEstadoOperacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int resultado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string textoResultado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string estado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fechaHoraEstado;
        
        public consultaEstadoOperacionResponseBody() {
        }
        
        public consultaEstadoOperacionResponseBody(int resultado, string textoResultado, string estado, string fechaHoraEstado) {
            this.resultado = resultado;
            this.textoResultado = textoResultado;
            this.estado = estado;
            this.fechaHoraEstado = fechaHoraEstado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaEstadoPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaEstadoPago", Namespace="http://www.banred.com.uy/PagosBancos/", Order=0)]
        public VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoRequestBody Body;
        
        public consultaEstadoPagoRequest() {
        }
        
        public consultaEstadoPagoRequest(VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultaEstadoPagoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idAgenteExterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idOperacionAgente;
        
        public consultaEstadoPagoRequestBody() {
        }
        
        public consultaEstadoPagoRequestBody(string idAgenteExterno, string idOperacionAgente) {
            this.idAgenteExterno = idAgenteExterno;
            this.idOperacionAgente = idOperacionAgente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaEstadoPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaEstadoPagoResponse", Namespace="http://www.banred.com.uy/PagosBancos/", Order=0)]
        public VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoResponseBody Body;
        
        public consultaEstadoPagoResponse() {
        }
        
        public consultaEstadoPagoResponse(VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultaEstadoPagoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int resultado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string textoResultado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string estado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fechaHoraEstado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nroTransaccion;
        
        public consultaEstadoPagoResponseBody() {
        }
        
        public consultaEstadoPagoResponseBody(int resultado, string textoResultado, string estado, string fechaHoraEstado, string nroTransaccion) {
            this.resultado = resultado;
            this.textoResultado = textoResultado;
            this.estado = estado;
            this.fechaHoraEstado = fechaHoraEstado;
            this.nroTransaccion = nroTransaccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resetearEpinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="resetearEpin", Namespace="http://www.banred.com.uy/PagosBancos/", Order=0)]
        public VisaNet.Banred.Mock.WcfBanredTest.resetearEpinRequestBody Body;
        
        public resetearEpinRequest() {
        }
        
        public resetearEpinRequest(VisaNet.Banred.Mock.WcfBanredTest.resetearEpinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class resetearEpinRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idAgenteExterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipoDoc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nroDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ePinNuevo;
        
        public resetearEpinRequestBody() {
        }
        
        public resetearEpinRequestBody(string idAgenteExterno, string tipoDoc, string nroDocumento, string ePinNuevo) {
            this.idAgenteExterno = idAgenteExterno;
            this.tipoDoc = tipoDoc;
            this.nroDocumento = nroDocumento;
            this.ePinNuevo = ePinNuevo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resetearEpinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="resetearEpinResponse", Namespace="http://www.banred.com.uy/PagosBancos/", Order=0)]
        public VisaNet.Banred.Mock.WcfBanredTest.resetearEpinResponseBody Body;
        
        public resetearEpinResponse() {
        }
        
        public resetearEpinResponse(VisaNet.Banred.Mock.WcfBanredTest.resetearEpinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class resetearEpinResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int resultado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string textoResultado;
        
        public resetearEpinResponseBody() {
        }
        
        public resetearEpinResponseBody(int resultado, string textoResultado) {
            this.resultado = resultado;
            this.textoResultado = textoResultado;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PagosBancosChannel : VisaNet.Banred.Mock.WcfBanredTest.PagosBancos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagosBancosClient : System.ServiceModel.ClientBase<VisaNet.Banred.Mock.WcfBanredTest.PagosBancos>, VisaNet.Banred.Mock.WcfBanredTest.PagosBancos {
        
        public PagosBancosClient() {
        }
        
        public PagosBancosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagosBancosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagosBancosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagosBancosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesResponse VisaNet.Banred.Mock.WcfBanredTest.PagosBancos.consultaEntesDisponibles(VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesRequest request) {
            return base.Channel.consultaEntesDisponibles(request);
        }
        
        public int consultaEntesDisponibles(string idAgenteExterno, out string textoResultado, out string listaEntes) {
            VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesRequest inValue = new VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesRequest();
            inValue.Body = new VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesRequestBody();
            inValue.Body.idAgenteExterno = idAgenteExterno;
            VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesResponse retVal = ((VisaNet.Banred.Mock.WcfBanredTest.PagosBancos)(this)).consultaEntesDisponibles(inValue);
            textoResultado = retVal.Body.textoResultado;
            listaEntes = retVal.Body.listaEntes;
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesResponse> VisaNet.Banred.Mock.WcfBanredTest.PagosBancos.consultaEntesDisponiblesAsync(VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesRequest request) {
            return base.Channel.consultaEntesDisponiblesAsync(request);
        }
        
        public System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesResponse> consultaEntesDisponiblesAsync(string idAgenteExterno) {
            VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesRequest inValue = new VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesRequest();
            inValue.Body = new VisaNet.Banred.Mock.WcfBanredTest.consultaEntesDisponiblesRequestBody();
            inValue.Body.idAgenteExterno = idAgenteExterno;
            return ((VisaNet.Banred.Mock.WcfBanredTest.PagosBancos)(this)).consultaEntesDisponiblesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteResponse VisaNet.Banred.Mock.WcfBanredTest.PagosBancos.consultaFacturasEnte(VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteRequest request) {
            return base.Channel.consultaFacturasEnte(request);
        }
        
        public int consultaFacturasEnte(string idAgenteExterno, string codigoEnte, string codigoCuentaEnte, out string textoResultado, out int cantFacturas, out string listaFacturas) {
            VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteRequest inValue = new VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteRequest();
            inValue.Body = new VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteRequestBody();
            inValue.Body.idAgenteExterno = idAgenteExterno;
            inValue.Body.codigoEnte = codigoEnte;
            inValue.Body.codigoCuentaEnte = codigoCuentaEnte;
            VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteResponse retVal = ((VisaNet.Banred.Mock.WcfBanredTest.PagosBancos)(this)).consultaFacturasEnte(inValue);
            textoResultado = retVal.Body.textoResultado;
            cantFacturas = retVal.Body.cantFacturas;
            listaFacturas = retVal.Body.listaFacturas;
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteResponse> VisaNet.Banred.Mock.WcfBanredTest.PagosBancos.consultaFacturasEnteAsync(VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteRequest request) {
            return base.Channel.consultaFacturasEnteAsync(request);
        }
        
        public System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteResponse> consultaFacturasEnteAsync(string idAgenteExterno, string codigoEnte, string codigoCuentaEnte) {
            VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteRequest inValue = new VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteRequest();
            inValue.Body = new VisaNet.Banred.Mock.WcfBanredTest.consultaFacturasEnteRequestBody();
            inValue.Body.idAgenteExterno = idAgenteExterno;
            inValue.Body.codigoEnte = codigoEnte;
            inValue.Body.codigoCuentaEnte = codigoCuentaEnte;
            return ((VisaNet.Banred.Mock.WcfBanredTest.PagosBancos)(this)).consultaFacturasEnteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteResponse VisaNet.Banred.Mock.WcfBanredTest.PagosBancos.pagarFacturaEnte(VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteRequest request) {
            return base.Channel.pagarFacturaEnte(request);
        }
        
        public int pagarFacturaEnte(string idAgenteExterno, string codigoEnte, string codigoCuentaEnte, string nroFactura, string montoPago, string MontoDescuentoIVA, string monedaPago, string fechaVencimiento, string idOperacionAgente, string firmaDigital, out string textoResultado, out string nroTransaccion, out string fechaHoraPago) {
            VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteRequest inValue = new VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteRequest();
            inValue.Body = new VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteRequestBody();
            inValue.Body.idAgenteExterno = idAgenteExterno;
            inValue.Body.codigoEnte = codigoEnte;
            inValue.Body.codigoCuentaEnte = codigoCuentaEnte;
            inValue.Body.nroFactura = nroFactura;
            inValue.Body.montoPago = montoPago;
            inValue.Body.MontoDescuentoIVA = MontoDescuentoIVA;
            inValue.Body.monedaPago = monedaPago;
            inValue.Body.fechaVencimiento = fechaVencimiento;
            inValue.Body.idOperacionAgente = idOperacionAgente;
            inValue.Body.firmaDigital = firmaDigital;
            VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteResponse retVal = ((VisaNet.Banred.Mock.WcfBanredTest.PagosBancos)(this)).pagarFacturaEnte(inValue);
            textoResultado = retVal.Body.textoResultado;
            nroTransaccion = retVal.Body.nroTransaccion;
            fechaHoraPago = retVal.Body.fechaHoraPago;
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteResponse> VisaNet.Banred.Mock.WcfBanredTest.PagosBancos.pagarFacturaEnteAsync(VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteRequest request) {
            return base.Channel.pagarFacturaEnteAsync(request);
        }
        
        public System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteResponse> pagarFacturaEnteAsync(string idAgenteExterno, string codigoEnte, string codigoCuentaEnte, string nroFactura, string montoPago, string MontoDescuentoIVA, string monedaPago, string fechaVencimiento, string idOperacionAgente, string firmaDigital) {
            VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteRequest inValue = new VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteRequest();
            inValue.Body = new VisaNet.Banred.Mock.WcfBanredTest.pagarFacturaEnteRequestBody();
            inValue.Body.idAgenteExterno = idAgenteExterno;
            inValue.Body.codigoEnte = codigoEnte;
            inValue.Body.codigoCuentaEnte = codigoCuentaEnte;
            inValue.Body.nroFactura = nroFactura;
            inValue.Body.montoPago = montoPago;
            inValue.Body.MontoDescuentoIVA = MontoDescuentoIVA;
            inValue.Body.monedaPago = monedaPago;
            inValue.Body.fechaVencimiento = fechaVencimiento;
            inValue.Body.idOperacionAgente = idOperacionAgente;
            inValue.Body.firmaDigital = firmaDigital;
            return ((VisaNet.Banred.Mock.WcfBanredTest.PagosBancos)(this)).pagarFacturaEnteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionResponse VisaNet.Banred.Mock.WcfBanredTest.PagosBancos.confirmarOperacion(VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionRequest request) {
            return base.Channel.confirmarOperacion(request);
        }
        
        public int confirmarOperacion(string idAgenteExterno, string idOperacionExterna, string status, string idOperacionAgente, string firmaDigital, out string textoResultado, out int nroTransaccionExterna, out string fechaHoraConfirmacion) {
            VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionRequest inValue = new VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionRequest();
            inValue.Body = new VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionRequestBody();
            inValue.Body.idAgenteExterno = idAgenteExterno;
            inValue.Body.idOperacionExterna = idOperacionExterna;
            inValue.Body.status = status;
            inValue.Body.idOperacionAgente = idOperacionAgente;
            inValue.Body.firmaDigital = firmaDigital;
            VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionResponse retVal = ((VisaNet.Banred.Mock.WcfBanredTest.PagosBancos)(this)).confirmarOperacion(inValue);
            textoResultado = retVal.Body.textoResultado;
            nroTransaccionExterna = retVal.Body.nroTransaccionExterna;
            fechaHoraConfirmacion = retVal.Body.fechaHoraConfirmacion;
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionResponse> VisaNet.Banred.Mock.WcfBanredTest.PagosBancos.confirmarOperacionAsync(VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionRequest request) {
            return base.Channel.confirmarOperacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionResponse> confirmarOperacionAsync(string idAgenteExterno, string idOperacionExterna, string status, string idOperacionAgente, string firmaDigital) {
            VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionRequest inValue = new VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionRequest();
            inValue.Body = new VisaNet.Banred.Mock.WcfBanredTest.confirmarOperacionRequestBody();
            inValue.Body.idAgenteExterno = idAgenteExterno;
            inValue.Body.idOperacionExterna = idOperacionExterna;
            inValue.Body.status = status;
            inValue.Body.idOperacionAgente = idOperacionAgente;
            inValue.Body.firmaDigital = firmaDigital;
            return ((VisaNet.Banred.Mock.WcfBanredTest.PagosBancos)(this)).confirmarOperacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionResponse VisaNet.Banred.Mock.WcfBanredTest.PagosBancos.consultaEstadoOperacion(VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionRequest request) {
            return base.Channel.consultaEstadoOperacion(request);
        }
        
        public int consultaEstadoOperacion(string idAgenteExterno, string idOperacionExterna, out string textoResultado, out string estado, out string fechaHoraEstado) {
            VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionRequest inValue = new VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionRequest();
            inValue.Body = new VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionRequestBody();
            inValue.Body.idAgenteExterno = idAgenteExterno;
            inValue.Body.idOperacionExterna = idOperacionExterna;
            VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionResponse retVal = ((VisaNet.Banred.Mock.WcfBanredTest.PagosBancos)(this)).consultaEstadoOperacion(inValue);
            textoResultado = retVal.Body.textoResultado;
            estado = retVal.Body.estado;
            fechaHoraEstado = retVal.Body.fechaHoraEstado;
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionResponse> VisaNet.Banred.Mock.WcfBanredTest.PagosBancos.consultaEstadoOperacionAsync(VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionRequest request) {
            return base.Channel.consultaEstadoOperacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionResponse> consultaEstadoOperacionAsync(string idAgenteExterno, string idOperacionExterna) {
            VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionRequest inValue = new VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionRequest();
            inValue.Body = new VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoOperacionRequestBody();
            inValue.Body.idAgenteExterno = idAgenteExterno;
            inValue.Body.idOperacionExterna = idOperacionExterna;
            return ((VisaNet.Banred.Mock.WcfBanredTest.PagosBancos)(this)).consultaEstadoOperacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoResponse VisaNet.Banred.Mock.WcfBanredTest.PagosBancos.consultaEstadoPago(VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoRequest request) {
            return base.Channel.consultaEstadoPago(request);
        }
        
        public int consultaEstadoPago(string idAgenteExterno, string idOperacionAgente, out string textoResultado, out string estado, out string fechaHoraEstado, out string nroTransaccion) {
            VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoRequest inValue = new VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoRequest();
            inValue.Body = new VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoRequestBody();
            inValue.Body.idAgenteExterno = idAgenteExterno;
            inValue.Body.idOperacionAgente = idOperacionAgente;
            VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoResponse retVal = ((VisaNet.Banred.Mock.WcfBanredTest.PagosBancos)(this)).consultaEstadoPago(inValue);
            textoResultado = retVal.Body.textoResultado;
            estado = retVal.Body.estado;
            fechaHoraEstado = retVal.Body.fechaHoraEstado;
            nroTransaccion = retVal.Body.nroTransaccion;
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoResponse> VisaNet.Banred.Mock.WcfBanredTest.PagosBancos.consultaEstadoPagoAsync(VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoRequest request) {
            return base.Channel.consultaEstadoPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoResponse> consultaEstadoPagoAsync(string idAgenteExterno, string idOperacionAgente) {
            VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoRequest inValue = new VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoRequest();
            inValue.Body = new VisaNet.Banred.Mock.WcfBanredTest.consultaEstadoPagoRequestBody();
            inValue.Body.idAgenteExterno = idAgenteExterno;
            inValue.Body.idOperacionAgente = idOperacionAgente;
            return ((VisaNet.Banred.Mock.WcfBanredTest.PagosBancos)(this)).consultaEstadoPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VisaNet.Banred.Mock.WcfBanredTest.resetearEpinResponse VisaNet.Banred.Mock.WcfBanredTest.PagosBancos.resetearEpin(VisaNet.Banred.Mock.WcfBanredTest.resetearEpinRequest request) {
            return base.Channel.resetearEpin(request);
        }
        
        public int resetearEpin(string idAgenteExterno, string tipoDoc, string nroDocumento, string ePinNuevo, out string textoResultado) {
            VisaNet.Banred.Mock.WcfBanredTest.resetearEpinRequest inValue = new VisaNet.Banred.Mock.WcfBanredTest.resetearEpinRequest();
            inValue.Body = new VisaNet.Banred.Mock.WcfBanredTest.resetearEpinRequestBody();
            inValue.Body.idAgenteExterno = idAgenteExterno;
            inValue.Body.tipoDoc = tipoDoc;
            inValue.Body.nroDocumento = nroDocumento;
            inValue.Body.ePinNuevo = ePinNuevo;
            VisaNet.Banred.Mock.WcfBanredTest.resetearEpinResponse retVal = ((VisaNet.Banred.Mock.WcfBanredTest.PagosBancos)(this)).resetearEpin(inValue);
            textoResultado = retVal.Body.textoResultado;
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.resetearEpinResponse> VisaNet.Banred.Mock.WcfBanredTest.PagosBancos.resetearEpinAsync(VisaNet.Banred.Mock.WcfBanredTest.resetearEpinRequest request) {
            return base.Channel.resetearEpinAsync(request);
        }
        
        public System.Threading.Tasks.Task<VisaNet.Banred.Mock.WcfBanredTest.resetearEpinResponse> resetearEpinAsync(string idAgenteExterno, string tipoDoc, string nroDocumento, string ePinNuevo) {
            VisaNet.Banred.Mock.WcfBanredTest.resetearEpinRequest inValue = new VisaNet.Banred.Mock.WcfBanredTest.resetearEpinRequest();
            inValue.Body = new VisaNet.Banred.Mock.WcfBanredTest.resetearEpinRequestBody();
            inValue.Body.idAgenteExterno = idAgenteExterno;
            inValue.Body.tipoDoc = tipoDoc;
            inValue.Body.nroDocumento = nroDocumento;
            inValue.Body.ePinNuevo = ePinNuevo;
            return ((VisaNet.Banred.Mock.WcfBanredTest.PagosBancos)(this)).resetearEpinAsync(inValue);
        }
    }
}
