//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaNet.Common.Resource.Audit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuditResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisaNet.Common.Resource.Audit.AuditResources", typeof(AuditResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios anónimos.
        /// </summary>
        public static string AnonymousUsers {
            get {
                return ResourceManager.GetString("AnonymousUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios de la aplicación.
        /// </summary>
        public static string ApplicationUsers {
            get {
                return ResourceManager.GetString("ApplicationUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de registro de auditoría.
        /// </summary>
        public static string AuditLogDetails {
            get {
                return ResourceManager.GetString("AuditLogDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de auditoría.
        /// </summary>
        public static string AuditLogs {
            get {
                return ResourceManager.GetString("AuditLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos programados.
        /// </summary>
        public static string AutomaticPayments {
            get {
                return ResourceManager.GetString("AutomaticPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bancos.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas.
        /// </summary>
        public static string Bills {
            get {
                return ResourceManager.GetString("Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIN.
        /// </summary>
        public static string Bin {
            get {
                return ResourceManager.GetString("Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociación entre BIN y Grupo de BIN.
        /// </summary>
        public static string BinBinGroups {
            get {
                return ResourceManager.GetString("BinBinGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de BIN.
        /// </summary>
        public static string BinGroups {
            get {
                return ResourceManager.GetString("BinGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociación entre Grupo de BIN y Servicios.
        /// </summary>
        public static string BinGroupServices {
            get {
                return ResourceManager.GetString("BinGroupServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjetas.
        /// </summary>
        public static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conciliación Banred.
        /// </summary>
        public static string ConciliationBanred {
            get {
                return ResourceManager.GetString("ConciliationBanred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conciliación CyberSource.
        /// </summary>
        public static string ConciliationCybersource {
            get {
                return ResourceManager.GetString("ConciliationCybersource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conciliación Sistarbanc.
        /// </summary>
        public static string ConciliationSistarbanc {
            get {
                return ResourceManager.GetString("ConciliationSistarbanc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conciliación Sucive.
        /// </summary>
        public static string ConciliationSucive {
            get {
                return ResourceManager.GetString("ConciliationSucive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resúmen de conciliación.
        /// </summary>
        public static string ConciliationSummary {
            get {
                return ResourceManager.GetString("ConciliationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conciliación Portal.
        /// </summary>
        public static string ConciliationVisanet {
            get {
                return ResourceManager.GetString("ConciliationVisanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conciliación Visanet.
        /// </summary>
        public static string ConciliationVisanetCallback {
            get {
                return ResourceManager.GetString("ConciliationVisanetCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactos.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de errores de CyberSource.
        /// </summary>
        public static string CybersourceErrorGroups {
            get {
                return ResourceManager.GetString("CybersourceErrorGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores de CyberSource.
        /// </summary>
        public static string CybersourceErrors {
            get {
                return ResourceManager.GetString("CybersourceErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuentos.
        /// </summary>
        public static string Discounts {
            get {
                return ResourceManager.GetString("Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails.
        /// </summary>
        public static string Emails {
            get {
                return ResourceManager.GetString("Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas frecuentes.
        /// </summary>
        public static string Faqs {
            get {
                return ResourceManager.GetString("Faqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaciones Backend.
        /// </summary>
        public static string FixedNotifications {
            get {
                return ResourceManager.GetString("FixedNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionalidades.
        /// </summary>
        public static string Functionalities {
            get {
                return ResourceManager.GetString("Functionalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de funcionalidades.
        /// </summary>
        public static string FunctionalitiesGroups {
            get {
                return ResourceManager.GetString("FunctionalitiesGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway.
        /// </summary>
        public static string Gateway {
            get {
                return ResourceManager.GetString("Gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos auxiliares de carretera.
        /// </summary>
        public static string HighwayAuxiliarDatas {
            get {
                return ResourceManager.GetString("HighwayAuxiliarDatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas de carretera.
        /// </summary>
        public static string HighwayBills {
            get {
                return ResourceManager.GetString("HighwayBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores en emails de carretera.
        /// </summary>
        public static string HighwayEmailErrors {
            get {
                return ResourceManager.GetString("HighwayEmailErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails de carretera.
        /// </summary>
        public static string HighwayEmails {
            get {
                return ResourceManager.GetString("HighwayEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página de inicio.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ítems de la página de inicio.
        /// </summary>
        public static string HomePageItems {
            get {
                return ResourceManager.GetString("HomePageItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imágenes.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretadores.
        /// </summary>
        public static string Interpreters {
            get {
                return ResourceManager.GetString("Interpreters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles de usuarios LDAP.
        /// </summary>
        public static string LDAPBaseUserRoles {
            get {
                return ResourceManager.GetString("LDAPBaseUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios LDAP.
        /// </summary>
        public static string LDAPBaseUsers {
            get {
                return ResourceManager.GetString("LDAPBaseUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas de API LIF.
        /// </summary>
        public static string LifApiBills {
            get {
                return ResourceManager.GetString("LifApiBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locaciones.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros de pago de CyberSource.
        /// </summary>
        public static string LogPaymentCyberSources {
            get {
                return ResourceManager.GetString("LogPaymentCyberSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios de Membership.
        /// </summary>
        public static string MembershipUsers {
            get {
                return ResourceManager.GetString("MembershipUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de notifiación de nueva factura.
        /// </summary>
        public static string NewBillNotificationInfo {
            get {
                return ResourceManager.GetString("NewBillNotificationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración de notificaciones.
        /// </summary>
        public static string NotificationConfigs {
            get {
                return ResourceManager.GetString("NotificationConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUMP de Configuración de notificaciones.
        /// </summary>
        public static string NotificationMessagesDump {
            get {
                return ResourceManager.GetString("NotificationMessagesDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaciones Backend.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Páginas.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificadores de pagos.
        /// </summary>
        public static string PaymentsIdentifiers {
            get {
                return ResourceManager.GetString("PaymentsIdentifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos programados pendientes.
        /// </summary>
        public static string PendingAutomaticPayments {
            get {
                return ResourceManager.GetString("PendingAutomaticPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histórico de procesos.
        /// </summary>
        public static string ProcessHistory {
            get {
                return ResourceManager.GetString("ProcessHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promociones.
        /// </summary>
        public static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuotas.
        /// </summary>
        public static string Quotations {
            get {
                return ResourceManager.GetString("Quotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista de reporte de pagos programados.
        /// </summary>
        public static string ReportAutomaticPaymentView {
            get {
                return ResourceManager.GetString("ReportAutomaticPaymentView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista de reporte de servicios asociados.
        /// </summary>
        public static string ReportServiceAssociatedView {
            get {
                return ResourceManager.GetString("ReportServiceAssociatedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista de reporte de transacciones.
        /// </summary>
        public static string ReportTransactionView {
            get {
                return ResourceManager.GetString("ReportTransactionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociación entre Rol y Acción.
        /// </summary>
        public static string RoleActions {
            get {
                return ResourceManager.GetString("RoleActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails de servicios habilitados.
        /// </summary>
        public static string ServiceEnableEmails {
            get {
                return ResourceManager.GetString("ServiceEnableEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway de servicios.
        /// </summary>
        public static string ServiceGateway {
            get {
                return ResourceManager.GetString("ServiceGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios asociados.
        /// </summary>
        public static string ServicesAssociated {
            get {
                return ResourceManager.GetString("ServicesAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociación entre servicios asociados y tarjetas.
        /// </summary>
        public static string ServicesAssociatedCards {
            get {
                return ResourceManager.GetString("ServicesAssociatedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorías de servicios.
        /// </summary>
        public static string ServicesCategories {
            get {
                return ResourceManager.GetString("ServicesCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios Sistarbanc.
        /// </summary>
        public static string SistarbancUser {
            get {
                return ResourceManager.GetString("SistarbancUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string Sms {
            get {
                return ResourceManager.GetString("Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suscriptores.
        /// </summary>
        public static string Subscribers {
            get {
                return ResourceManager.GetString("Subscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios del sistema.
        /// </summary>
        public static string SystemUsers {
            get {
                return ResourceManager.GetString("SystemUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC33.
        /// </summary>
        public static string Tc33 {
            get {
                return ResourceManager.GetString("Tc33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacciones de TC33.
        /// </summary>
        public static string Tc33Transactions {
            get {
                return ResourceManager.GetString("Tc33Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook de bajas.
        /// </summary>
        public static string WebhookDowns {
            get {
                return ResourceManager.GetString("WebhookDowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook de nuevas asociaciones.
        /// </summary>
        public static string WebhookNewAssociations {
            get {
                return ResourceManager.GetString("WebhookNewAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook registros.
        /// </summary>
        public static string WebhookRegistrations {
            get {
                return ResourceManager.GetString("WebhookRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos auxiliares de facturas online para WebService.
        /// </summary>
        public static string WsBillPaymentOnlineAuxiliarFields {
            get {
                return ResourceManager.GetString("WsBillPaymentOnlineAuxiliarFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas online para pagos para WebService.
        /// </summary>
        public static string WsBillPaymentOnlines {
            get {
                return ResourceManager.GetString("WsBillPaymentOnlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultas de facturas para WebService.
        /// </summary>
        public static string WsBillQueries {
            get {
                return ResourceManager.GetString("WsBillQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminaciones de tarjetas para WebService.
        /// </summary>
        public static string WsCardRemoves {
            get {
                return ResourceManager.GetString("WsCardRemoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultas de comercios para WebService.
        /// </summary>
        public static string WsCommerceQueries {
            get {
                return ResourceManager.GetString("WsCommerceQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelaciones de pagos para WebService.
        /// </summary>
        public static string WsPaymentCancellations {
            get {
                return ResourceManager.GetString("WsPaymentCancellations", resourceCulture);
            }
        }
    }
}
