//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sucive.MO_15 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="GeoTribUy", ConfigurationName="MO_15.Ws15ReversobSoapPort")]
    public interface Ws15ReversobSoapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="GeoTribUyaction/AWS15REVERSOB.Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sucive.MO_15.ExecuteResponse Execute(Sucive.MO_15.ExecuteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="GeoTribUyaction/AWS15REVERSOB.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Sucive.MO_15.ExecuteResponse> ExecuteAsync(Sucive.MO_15.ExecuteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SDT_ListaAnu.SDT_ListaAnuItem", Namespace="GeoTribUy")]
    public partial class SDT_ListaAnuSDT_ListaAnuItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoDatoField;
        
        private string datoField;
        
        /// <remarks/>
        public string TipoDato {
            get {
                return this.tipoDatoField;
            }
            set {
                this.tipoDatoField = value;
                this.RaisePropertyChanged("TipoDato");
            }
        }
        
        /// <remarks/>
        public string Dato {
            get {
                return this.datoField;
            }
            set {
                this.datoField = value;
                this.RaisePropertyChanged("Dato");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ws15Reversob.Execute", WrapperNamespace="GeoTribUy", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="GeoTribUy", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Sucive.MO_15.SDT_ListaAnuSDT_ListaAnuItem[] Sdt_listaanu;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(Sucive.MO_15.SDT_ListaAnuSDT_ListaAnuItem[] Sdt_listaanu) {
            this.Sdt_listaanu = Sdt_listaanu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ws15Reversob.ExecuteResponse", WrapperNamespace="GeoTribUy", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="GeoTribUy", Order=0)]
        public string Codigoretorno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="GeoTribUy", Order=1)]
        public string Mensajeretorno;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(string Codigoretorno, string Mensajeretorno) {
            this.Codigoretorno = Codigoretorno;
            this.Mensajeretorno = Mensajeretorno;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Ws15ReversobSoapPortChannel : Sucive.MO_15.Ws15ReversobSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Ws15ReversobSoapPortClient : System.ServiceModel.ClientBase<Sucive.MO_15.Ws15ReversobSoapPort>, Sucive.MO_15.Ws15ReversobSoapPort {
        
        public Ws15ReversobSoapPortClient() {
        }
        
        public Ws15ReversobSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ws15ReversobSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws15ReversobSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws15ReversobSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sucive.MO_15.ExecuteResponse Sucive.MO_15.Ws15ReversobSoapPort.Execute(Sucive.MO_15.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public string Execute(Sucive.MO_15.SDT_ListaAnuSDT_ListaAnuItem[] Sdt_listaanu, out string Mensajeretorno) {
            Sucive.MO_15.ExecuteRequest inValue = new Sucive.MO_15.ExecuteRequest();
            inValue.Sdt_listaanu = Sdt_listaanu;
            Sucive.MO_15.ExecuteResponse retVal = ((Sucive.MO_15.Ws15ReversobSoapPort)(this)).Execute(inValue);
            Mensajeretorno = retVal.Mensajeretorno;
            return retVal.Codigoretorno;
        }
        
        public System.Threading.Tasks.Task<Sucive.MO_15.ExecuteResponse> ExecuteAsync(Sucive.MO_15.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
    }
}
