//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaNet.Common.Resource.Presentation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PresentationCallCenterStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PresentationCallCenterStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisaNet.Common.Resource.Presentation.PresentationCallCenterStrings", typeof(PresentationCallCenterStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario indicado no existe..
        /// </summary>
        public static string Application_User_Not_Exist {
            get {
                return ResourceManager.GetString("Application_User_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoría.
        /// </summary>
        public static string AuditLog {
            get {
                return ResourceManager.GetString("AuditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoría.
        /// </summary>
        public static string Header_AuditLog {
            get {
                return ResourceManager.GetString("Header_AuditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Center.
        /// </summary>
        public static string Header_CallCenter {
            get {
                return ResourceManager.GetString("Header_CallCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Call Center.
        /// </summary>
        public static string Header_CallCenterUser {
            get {
                return ResourceManager.GetString("Header_CallCenterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        public static string Header_Dashboard {
            get {
                return ResourceManager.GetString("Header_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Header_Email {
            get {
                return ResourceManager.GetString("Header_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string Header_PhoneNumber {
            get {
                return ResourceManager.GetString("Header_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitio público.
        /// </summary>
        public static string Header_PublicSyte {
            get {
                return ResourceManager.GetString("Header_PublicSyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Header_User {
            get {
                return ResourceManager.GetString("Header_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivar usuario.
        /// </summary>
        public static string InactivateUser {
            get {
                return ResourceManager.GetString("InactivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Sitio Público.
        /// </summary>
        public static string User_Confirmation {
            get {
                return ResourceManager.GetString("User_Confirmation", resourceCulture);
            }
        }
    }
}
