//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaNet.Common.Resource.Presentation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PresentationVisaNetOnStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PresentationVisaNetOnStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisaNet.Common.Resource.Presentation.PresentationVisaNetOnStrings", typeof(PresentationVisaNetOnStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El comercio inhabilito el token generado para el pago de facturas. Póngase en contacto con ellos..
        /// </summary>
        public static string AccessToken_Canceled {
            get {
                return ResourceManager.GetString("AccessToken_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Apellido excede el largo máximo (50)..
        /// </summary>
        public static string FieldApellidoMax {
            get {
                return ResourceManager.GetString("FieldApellidoMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo CI excede el largo máximo (50)..
        /// </summary>
        public static string FieldCIMax {
            get {
                return ResourceManager.GetString("FieldCIMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Concepto excede el largo máximo (100)..
        /// </summary>
        public static string FieldConceptoMax {
            get {
                return ResourceManager.GetString("FieldConceptoMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Direccion excede el largo máximo (50)..
        /// </summary>
        public static string FieldDireccionMax {
            get {
                return ResourceManager.GetString("FieldDireccionMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Email excede el largo máximo (50)..
        /// </summary>
        public static string FieldEmailMax {
            get {
                return ResourceManager.GetString("FieldEmailMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo FacturaConsFinal excede el largo máximo (1)..
        /// </summary>
        public static string FieldFacturaConsFinalMax {
            get {
                return ResourceManager.GetString("FieldFacturaConsFinalMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo FacturaCuota excede el largo máximo (1)..
        /// </summary>
        public static string FieldFacturaCuotaMax {
            get {
                return ResourceManager.GetString("FieldFacturaCuotaMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo FacturaDescripcion excede el largo máximo (100)..
        /// </summary>
        public static string FieldFacturaDescripcionMax {
            get {
                return ResourceManager.GetString("FieldFacturaDescripcionMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo FacturaFecha excede el largo máximo (8)..
        /// </summary>
        public static string FieldFacturaFechaMax {
            get {
                return ResourceManager.GetString("FieldFacturaFechaMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo FacturaIdentificador excede el largo máximo (100)..
        /// </summary>
        public static string FieldFacturaIdentificadorMax {
            get {
                return ResourceManager.GetString("FieldFacturaIdentificadorMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo FacturaImporteGravado excede el largo máximo (12)..
        /// </summary>
        public static string FieldFacturaImporteGravadoMax {
            get {
                return ResourceManager.GetString("FieldFacturaImporteGravadoMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo FacturaImporte excede el largo máximo (12)..
        /// </summary>
        public static string FieldFacturaImporteMax {
            get {
                return ResourceManager.GetString("FieldFacturaImporteMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo FacturaMoneda excede el largo máximo (1)..
        /// </summary>
        public static string FieldFacturaMonedaMax {
            get {
                return ResourceManager.GetString("FieldFacturaMonedaMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo IdApp excede el largo máximo (50)..
        /// </summary>
        public static string FieldIdAppMax {
            get {
                return ResourceManager.GetString("FieldIdAppMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo IdOperacion excede el largo máximo (50)..
        /// </summary>
        public static string FieldIdOperacionMax {
            get {
                return ResourceManager.GetString("FieldIdOperacionMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo IdUsuario excede el largo máximo (36)..
        /// </summary>
        public static string FieldIdUsuarioMax {
            get {
                return ResourceManager.GetString("FieldIdUsuarioMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Importe excede el largo máximo (12)..
        /// </summary>
        public static string FieldImporteMax {
            get {
                return ResourceManager.GetString("FieldImporteMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo MerchantId excede el largo máximo (25)..
        /// </summary>
        public static string FieldMerchantIdMax {
            get {
                return ResourceManager.GetString("FieldMerchantIdMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Movil excede el largo máximo (50)..
        /// </summary>
        public static string FieldMovilMax {
            get {
                return ResourceManager.GetString("FieldMovilMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Nombre excede el largo máximo (50)..
        /// </summary>
        public static string FieldNombreMax {
            get {
                return ResourceManager.GetString("FieldNombreMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Orden excede el largo máximo (2)..
        /// </summary>
        public static string FieldOrdenMax {
            get {
                return ResourceManager.GetString("FieldOrdenMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo PermiteCambioEmail excede el largo máximo (1)..
        /// </summary>
        public static string FieldPermiteCambioEmailMax {
            get {
                return ResourceManager.GetString("FieldPermiteCambioEmailMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo PermiteRecordarUsuario excede el largo máximo (1)..
        /// </summary>
        public static string FieldPermiteRecordarUsuarioMax {
            get {
                return ResourceManager.GetString("FieldPermiteRecordarUsuarioMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo RefCliente1 excede el largo máximo (100)..
        /// </summary>
        public static string FieldRefCliente1Max {
            get {
                return ResourceManager.GetString("FieldRefCliente1Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo RefCliente2 excede el largo máximo (100)..
        /// </summary>
        public static string FieldRefCliente2Max {
            get {
                return ResourceManager.GetString("FieldRefCliente2Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo RefCliente3 excede el largo máximo (100)..
        /// </summary>
        public static string FieldRefCliente3Max {
            get {
                return ResourceManager.GetString("FieldRefCliente3Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo RefCliente4 excede el largo máximo (100)..
        /// </summary>
        public static string FieldRefCliente4Max {
            get {
                return ResourceManager.GetString("FieldRefCliente4Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo RefCliente5 excede el largo máximo (100)..
        /// </summary>
        public static string FieldRefCliente5Max {
            get {
                return ResourceManager.GetString("FieldRefCliente5Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo RefCliente6 excede el largo máximo (100)..
        /// </summary>
        public static string FieldRefCliente6Max {
            get {
                return ResourceManager.GetString("FieldRefCliente6Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo SendEmail excede el largo máximo (1)..
        /// </summary>
        public static string FieldSendEmailMax {
            get {
                return ResourceManager.GetString("FieldSendEmailMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Telefono excede el largo máximo (50)..
        /// </summary>
        public static string FieldTelefonoMax {
            get {
                return ResourceManager.GetString("FieldTelefonoMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo UrlCallback excede el largo máximo (255)..
        /// </summary>
        public static string FieldUrlCallbackMax {
            get {
                return ResourceManager.GetString("FieldUrlCallbackMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo campo Apellido es requerido..
        /// </summary>
        public static string RequiredFieldApellido {
            get {
                return ResourceManager.GetString("RequiredFieldApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo campo Dirección es requerido..
        /// </summary>
        public static string RequiredFieldDireccion {
            get {
                return ResourceManager.GetString("RequiredFieldDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo campo Email es requerido..
        /// </summary>
        public static string RequiredFieldEmail {
            get {
                return ResourceManager.GetString("RequiredFieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo campo FacturaConsFinal es requerido..
        /// </summary>
        public static string RequiredFieldFacturaConsFinal {
            get {
                return ResourceManager.GetString("RequiredFieldFacturaConsFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo campo FacturaIdentificador es requerido..
        /// </summary>
        public static string RequiredFieldFacturaIdentificador {
            get {
                return ResourceManager.GetString("RequiredFieldFacturaIdentificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo campo FacturaImporte es requerido..
        /// </summary>
        public static string RequiredFieldFacturaImporte {
            get {
                return ResourceManager.GetString("RequiredFieldFacturaImporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo campo FacturaMoneda es requerido..
        /// </summary>
        public static string RequiredFieldFacturaMoneda {
            get {
                return ResourceManager.GetString("RequiredFieldFacturaMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo campo FirmaDigital es requerido..
        /// </summary>
        public static string RequiredFieldFirmaDigital {
            get {
                return ResourceManager.GetString("RequiredFieldFirmaDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo campo IdApp es requerido..
        /// </summary>
        public static string RequiredFieldIdApp {
            get {
                return ResourceManager.GetString("RequiredFieldIdApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo campo IdOperacion es requerido..
        /// </summary>
        public static string RequiredFieldIdOperacion {
            get {
                return ResourceManager.GetString("RequiredFieldIdOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo campo IdUsuario es requerido..
        /// </summary>
        public static string RequiredFieldIdUsuario {
            get {
                return ResourceManager.GetString("RequiredFieldIdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo campo MerchantId es requerido..
        /// </summary>
        public static string RequiredFieldMerchantId {
            get {
                return ResourceManager.GetString("RequiredFieldMerchantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo campo Nombre es requerido..
        /// </summary>
        public static string RequiredFieldNombre {
            get {
                return ResourceManager.GetString("RequiredFieldNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo campo UrlCallback es requerido..
        /// </summary>
        public static string RequiredFieldUrlCallback {
            get {
                return ResourceManager.GetString("RequiredFieldUrlCallback", resourceCulture);
            }
        }
    }
}
