//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaNet.Common.Logging.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisaNet.Common.Logging.Resources.LogStrings", typeof(LogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicaciones.
        /// </summary>
        public static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La factura ({0}) ya se encuentra paga en el sistema..
        /// </summary>
        public static string Bill_Already_Paid {
            get {
                return ResourceManager.GetString("Bill_Already_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se genero un error al intentar persisitr esta factura. Ver logs para mas detalle. Transaccion {0}.
        /// </summary>
        public static string Bill_Save_Error {
            get {
                return ResourceManager.GetString("Bill_Save_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se genero un error al intentar persisitr esta factura pero la misma se notifico como paga ante el ente. Chequear disponibilidad de deuda ante la duda..
        /// </summary>
        public static string Bill_Save_Error_Callcenter {
            get {
                return ResourceManager.GetString("Bill_Save_Error_Callcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se elimino la transacción por error de factura. Transaccion {0}. Pasarela {1}.
        /// </summary>
        public static string Bill_Save_Error_Callcenter_Deleted {
            get {
                return ResourceManager.GetString("Bill_Save_Error_Callcenter_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se elimino la transacción por error de factura. Transaccion {0}. Pasarela {1}.
        /// </summary>
        public static string Bill_Save_Error_Deleted {
            get {
                return ResourceManager.GetString("Bill_Save_Error_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura paga: {0}, Transacción: {1}.
        /// </summary>
        public static string CallCenter_Payment_Bill_Success {
            get {
                return ResourceManager.GetString("CallCenter_Payment_Bill_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se canceló el pago debído a un error de comunicación. Transacción {0}..
        /// </summary>
        public static string CallCenter_Payment_Cancel {
            get {
                return ResourceManager.GetString("CallCenter_Payment_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha cancelado la transacción con éxito. Transacción: {0}.
        /// </summary>
        public static string CallCenter_Payment_Cancel_Success {
            get {
                return ResourceManager.GetString("CallCenter_Payment_Cancel_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizo un reverso de la transaccion en cybersource, id de transacción {0}.
        /// </summary>
        public static string CallCenter_Payment_Reverse_Success {
            get {
                return ResourceManager.GetString("CallCenter_Payment_Reverse_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacción finalizada con éxito. Transacción: {0}.
        /// </summary>
        public static string CallCenter_Payment_Success {
            get {
                return ResourceManager.GetString("CallCenter_Payment_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tarjeta {3} se asoció correctamente con el usuario {0} ({1} {2}),.
        /// </summary>
        public static string Card_finished {
            get {
                return ResourceManager.GetString("Card_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia el proceso de adhesión de una tarjeta para usuario {0}, tarjeta {3}.
        /// </summary>
        public static string Card_init {
            get {
                return ResourceManager.GetString("Card_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSVoidProcess.
        /// </summary>
        public static string CSVoidProcess {
            get {
                return ResourceManager.GetString("CSVoidProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llego una transaccion de Cybersource. Se inicia el análisis de la misma. Codigo {0}, Transacción {1}.
        /// </summary>
        public static string Cybersource_Analize_Init {
            get {
                return ResourceManager.GetString("Cybersource_Analize_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia el proceso de adhesión de debito para el usuario {0}, comercio y producto {1}.
        /// </summary>
        public static string Debit_Init {
            get {
                return ResourceManager.GetString("Debit_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por defecto.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaciones.
        /// </summary>
        public static string EmailNotification {
            get {
                return ResourceManager.GetString("EmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCs.
        /// </summary>
        public static string ErrorCs {
            get {
                return ResourceManager.GetString("ErrorCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        public static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocom.
        /// </summary>
        public static string Geocom {
            get {
                return ResourceManager.GetString("Geocom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carretera.
        /// </summary>
        public static string Highway {
            get {
                return ResourceManager.GetString("Highway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighwayFileProccess.
        /// </summary>
        public static string HighwayFileProccess {
            get {
                return ResourceManager.GetString("HighwayFileProccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error en cybersource {0}, usuario {1} ({2} {3}), servicio {4} (merchand id = {5}).
        /// </summary>
        public static string HighwaytCallBackError {
            get {
                return ResourceManager.GetString("HighwaytCallBackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia el proceso de cancelación por web service. IdApp: {0}, IdOperación {1}.
        /// </summary>
        public static string IntegrationService_Cancel_Init {
            get {
                return ResourceManager.GetString("IntegrationService_Cancel_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia el proceso de baja de tarjeta por web service. IdApp: {0}, IdOperación {1}.
        /// </summary>
        public static string IntegrationService_CardRemove_Init {
            get {
                return ResourceManager.GetString("IntegrationService_CardRemove_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia el proceso de pago por web service. IdApp: {0}, IdOperación {1}.
        /// </summary>
        public static string IntegrationService_Payment_Init {
            get {
                return ResourceManager.GetString("IntegrationService_Payment_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itaú.
        /// </summary>
        public static string Itau {
            get {
                return ResourceManager.GetString("Itau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto de la factura debe ser mayor a 0. Id operacion &apos;{0}&apos;, Monto &apos;{1}&apos;.
        /// </summary>
        public static string Log_Amount_Error {
            get {
                return ResourceManager.GetString("Log_Amount_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto gravado de la factura no puede ser menor a 0 ni mayor al monto total. Id operacion &apos;{0}&apos;, Monto gravado &apos;{1}&apos;.
        /// </summary>
        public static string Log_AmountTaxed_Error {
            get {
                return ResourceManager.GetString("Log_AmountTaxed_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjeta no encontrada. Id exterior de tarjeta  {0}.
        /// </summary>
        public static string Log_Card_Not_Found {
            get {
                return ResourceManager.GetString("Log_Card_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercio duplicado. CodComercio {0}, CodSucursal {1}, IdMerchant {3}, IdApp {2}.
        /// </summary>
        public static string Log_CommerceDuplicated {
            get {
                return ResourceManager.GetString("Log_CommerceDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercio no habilitado. CodComercio {0}, CodSucursal {1}, IdApp {2}.
        /// </summary>
        public static string Log_CommerceNotActive {
            get {
                return ResourceManager.GetString("Log_CommerceNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercio no encontrado. CodComercio {0}, CodSucursal {1}, IdMerchant {3}, IdApp {2}.
        /// </summary>
        public static string Log_CommerceNotFound {
            get {
                return ResourceManager.GetString("Log_CommerceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se genero un error al intentar generar el descuento correspondiente..
        /// </summary>
        public static string Log_DiscountError {
            get {
                return ResourceManager.GetString("Log_DiscountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio {0} no contiene al servicio de comercio {1} y sucursal {2}.
        /// </summary>
        public static string Log_ServiceFather_Error {
            get {
                return ResourceManager.GetString("Log_ServiceFather_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio {0} no esta habilitado para pagos por web service de VisaNetOn. CodComercio {1}, CodSucursal {2}, IdMerchant {3}.
        /// </summary>
        public static string Log_ServiceNotAllow_Wcf {
            get {
                return ResourceManager.GetString("Log_ServiceNotAllow_Wcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio asociado no encontrado. Nro de referencia {0}.
        /// </summary>
        public static string Log_ServiceNotFound {
            get {
                return ResourceManager.GetString("Log_ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se genero una expecion en el web service de integracion despues de haber notificado a Cybersource. Id Operation {0}, Trns {1}.
        /// </summary>
        public static string Log_WebService_Integration_AfterCs_Exception {
            get {
                return ResourceManager.GetString("Log_WebService_Integration_AfterCs_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se genero una expecion en el web service de integracion. Id Operation {0}.
        /// </summary>
        public static string Log_WebService_Integration_Exception {
            get {
                return ResourceManager.GetString("Log_WebService_Integration_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se incremento la cantidad de pagos programados realizados, servicio asociado {0}.
        /// </summary>
        public static string Payment_Automatic {
            get {
                return ResourceManager.GetString("Payment_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se persistio el registro de una nueva factura,id de factura {0}, id de transacción {1}.
        /// </summary>
        public static string Payment_Bill_Entity_Cretion {
            get {
                return ResourceManager.GetString("Payment_Bill_Entity_Cretion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo realizar la transacción en cybersoruce. Código de retorno: {0}. Transacción: {1}.
        /// </summary>
        public static string Payment_Cybersource_Bad_ReasonCode {
            get {
                return ResourceManager.GetString("Payment_Cybersource_Bad_ReasonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por error de comunicacion con las pasarelas, se procede a cancelar la transaccion en cybersource. Id de transacción {0}.
        /// </summary>
        public static string Payment_Cybersource_Cancel {
            get {
                return ResourceManager.GetString("Payment_Cybersource_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se cancelo la transaccion en cybersource, id de transacción {0}.
        /// </summary>
        public static string Payment_Cybersource_Cancel_Done {
            get {
                return ResourceManager.GetString("Payment_Cybersource_Cancel_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar realizar un reembolso luego de haber realizado un pago por medio de cybersource. Mensaje de error {0}, transaccion id {1}.
        /// </summary>
        public static string Payment_Cybersource_Cancel_Error {
            get {
                return ResourceManager.GetString("Payment_Cybersource_Cancel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error con las pasarelas, se procede a cancelar la transaccion en cybersource. Id de transacción {0}.
        /// </summary>
        public static string Payment_Cybersource_Cancel_Must {
            get {
                return ResourceManager.GetString("Payment_Cybersource_Cancel_Must", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de comunicación con Cybersource. La excepcion capturada fue CommunicationException. Id de transacción {0}.
        /// </summary>
        public static string Payment_Cybersource_Communication {
            get {
                return ResourceManager.GetString("Payment_Cybersource_Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE PRODUJO UN ERROR AL INTENTAR USAR EL WCF DE CYBERSOURCE, mensaje de error {0},  id de transacción {1}.
        /// </summary>
        public static string Payment_Cybersource_Error {
            get {
                return ResourceManager.GetString("Payment_Cybersource_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al comunicarce con Cybersource. La excepcion capturada fue FaultException. Id de transacción {0}.
        /// </summary>
        public static string Payment_Cybersource_Fault {
            get {
                return ResourceManager.GetString("Payment_Cybersource_Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se cancelo la transaccion (refund) en cybersource, id de transacción {0}.
        /// </summary>
        public static string Payment_Cybersource_Refund_Done {
            get {
                return ResourceManager.GetString("Payment_Cybersource_Refund_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar realizar un refund, mensaje de error {0}, id de transaccion {1}.
        /// </summary>
        public static string Payment_Cybersource_Refund_Error {
            get {
                return ResourceManager.GetString("Payment_Cybersource_Refund_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizo un reverso de la transaccion en cybersource, id de transacción {0}.
        /// </summary>
        public static string Payment_Cybersource_Reverse_Done {
            get {
                return ResourceManager.GetString("Payment_Cybersource_Reverse_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar realizar un reverso por medio de cybersource. Mensaje de error {0}, transaccion id {1}.
        /// </summary>
        public static string Payment_Cybersource_Reverse_Error {
            get {
                return ResourceManager.GetString("Payment_Cybersource_Reverse_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de comunicación con Cybersource. La excepcion capturada fue TimeoutExcepcion. Id de transacción {0}.
        /// </summary>
        public static string Payment_Cybersource_Timeout {
            get {
                return ResourceManager.GetString("Payment_Cybersource_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar realizar un void, mensaje de error {0}, id de transaccion {1}.
        /// </summary>
        public static string Payment_Cybersource_Void_Error {
            get {
                return ResourceManager.GetString("Payment_Cybersource_Void_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizo el pago con cybersource, id de transacción {0}, monto: {1}, moneda: {2}.
        /// </summary>
        public static string Payment_Cybersource_WCFPayment_Done {
            get {
                return ResourceManager.GetString("Payment_Cybersource_WCFPayment_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error en cybersource {0}, usuario {1} ({2} {3}), servicio {4} (merchand id = {5}).
        /// </summary>
        public static string Payment_cybersourceCallback_error {
            get {
                return ResourceManager.GetString("Payment_cybersourceCallback_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador de proceso de pago {0} para usuario  {1} ({2} {3}), servicio {4}.
        /// </summary>
        public static string Payment_CybersoureData {
            get {
                return ResourceManager.GetString("Payment_CybersoureData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termina el proceso de pago no registrado para usuario {0} ({1} {2}), servicio {3}, id de transacción {4}.
        /// </summary>
        public static string Payment_Done {
            get {
                return ResourceManager.GetString("Payment_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se persistio el registro de pago, id de transacción {0}.
        /// </summary>
        public static string Payment_Entity_Cretion {
            get {
                return ResourceManager.GetString("Payment_Entity_Cretion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE PRODUJO UN ERROR AL INTENTAR USAR LAS PASARELAS, POSIBLE ERROR DE DATOS, mensaje de error {0},  id de transacción {1}.
        /// </summary>
        public static string Payment_Gateway_ErroData {
            get {
                return ResourceManager.GetString("Payment_Gateway_ErroData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE PRODUJO UN ERROR AL INTENTAR PAGAR POR LA PASARELA PRINCIPAL, mensaje de error {0},  id de transacción {1}.
        /// </summary>
        public static string Payment_Gateway_Error {
            get {
                return ResourceManager.GetString("Payment_Gateway_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ecnontro otra pasarela de pago habilitada, id de transacción {0}.
        /// </summary>
        public static string Payment_Gateway_NoMore {
            get {
                return ResourceManager.GetString("Payment_Gateway_NoMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se intentara pagar por otra pasarela, id de transacción {0}.
        /// </summary>
        public static string Payment_Gateway_OtherWay {
            get {
                return ResourceManager.GetString("Payment_Gateway_OtherWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE PRODUJO UN ERROR AL INTENTAR PAGAR POR OTRA PASARELA, mensaje de error {0},  id de transacción {1}.
        /// </summary>
        public static string Payment_Gateway_OtherWayError {
            get {
                return ResourceManager.GetString("Payment_Gateway_OtherWayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtengo la pasarela por donde se deben marcar las facturas como pagas, id de transacción {0}.
        /// </summary>
        public static string Payment_GetGateway {
            get {
                return ResourceManager.GetString("Payment_GetGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia el proceso de pago no registrado para usuario {0} ({1} {2}), servicio {3}.
        /// </summary>
        public static string Payment_Init {
            get {
                return ResourceManager.GetString("Payment_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia el proceso de pago registrado para usuario {0} ({1} {2}), servicio {3}.
        /// </summary>
        public static string Payment_Loged_Init {
            get {
                return ResourceManager.GetString("Payment_Loged_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento notificar al ente por medio de pasarela Banred, id de transacción  {0}, nro factura {1}.
        /// </summary>
        public static string Payment_NotifyBanred {
            get {
                return ResourceManager.GetString("Payment_NotifyBanred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se notifico al ente por medio de pasarela Banred, id de transacción {0}, nro factura {1}, monto {2}, monto descuento iva{3}.
        /// </summary>
        public static string Payment_NotifyBanred_Done {
            get {
                return ResourceManager.GetString("Payment_NotifyBanred_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE PRODUJO UN ERROR AL INTENTAR NOTIFICAR A ENTE POR MEDIO DE BANRED, mensaje de error {0}, id de transacción {1}, nro factura {2}, montoPago {3}, monto grabado {4}.
        /// </summary>
        public static string Payment_NotifyBanred_Error {
            get {
                return ResourceManager.GetString("Payment_NotifyBanred_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifico al ente correspondiente por medio de la pasarela, id de transacción {0}.
        /// </summary>
        public static string Payment_NotifyGateway {
            get {
                return ResourceManager.GetString("Payment_NotifyGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se notifico al ente por medio de pasarela Geocom, id de transacción {0}, nro factura {1}.
        /// </summary>
        public static string Payment_NotifyGeocom_Done {
            get {
                return ResourceManager.GetString("Payment_NotifyGeocom_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar notificar al ente por medio de Geocom, mensaje de error {0}, id de transacción {1}, nro pre factura {2}.
        /// </summary>
        public static string Payment_NotifyGeocom_Error {
            get {
                return ResourceManager.GetString("Payment_NotifyGeocom_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento notificar al ente por medio de pasarela Carretera, id de transacción  {0}, nro factura {1}.
        /// </summary>
        public static string Payment_NotifyHighway {
            get {
                return ResourceManager.GetString("Payment_NotifyHighway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se notifico al ente por medio de pasarela Carretera, id de transacción {0}, nro factura {1}, monto {2}, monto descuento iva{3}.
        /// </summary>
        public static string Payment_NotifyHighway_Done {
            get {
                return ResourceManager.GetString("Payment_NotifyHighway_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE PRODUJO UN ERROR AL INTENTAR NOTIFICAR A ENTE POR MEDIO DE CARRETERA, mensaje de error {0}, id de transacción {1}, nro factura {2}, montoPago {3}, monto grabado {4}.
        /// </summary>
        public static string Payment_NotifyHighway_Error {
            get {
                return ResourceManager.GetString("Payment_NotifyHighway_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento notificar al ente por medio de pasarela Sistarbanc, id de transacción {0}.
        /// </summary>
        public static string Payment_NotifySistarbanc {
            get {
                return ResourceManager.GetString("Payment_NotifySistarbanc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se notifico al ente por medio de pasarela Sistarbanc, id de transacción {0}, nro factura {1}, id banco {2}, id usuario {3}.
        /// </summary>
        public static string Payment_NotifySistarbanc_Done {
            get {
                return ResourceManager.GetString("Payment_NotifySistarbanc_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE PRODUJO UN ERROR AL INTENTAR NOTIFICAR A ENTE POR MEDIO DE SISTARBANC, mensaje de error {0}, id de transacción {1}, nro factura {2}.
        /// </summary>
        public static string Payment_NotifySistarbanc_Error {
            get {
                return ResourceManager.GetString("Payment_NotifySistarbanc_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al interactuar con sistarbanc, el número de cuenta es invalido. Codigo de error 2.
        /// </summary>
        public static string Payment_NotifySistarbanc_Error2 {
            get {
                return ResourceManager.GetString("Payment_NotifySistarbanc_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al interactuar con sistarbanc, Factura ya paga, codigo de error 29.
        /// </summary>
        public static string Payment_NotifySistarbanc_Error29 {
            get {
                return ResourceManager.GetString("Payment_NotifySistarbanc_Error29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al interactuar con sistarbanc, no se pudo invocar el organizmo, codigo error 50.
        /// </summary>
        public static string Payment_NotifySistarbanc_Error50 {
            get {
                return ResourceManager.GetString("Payment_NotifySistarbanc_Error50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al interactuar con sistarbanc, el pago no respeta procedencia. Codigo de error 57.
        /// </summary>
        public static string Payment_NotifySistarbanc_Error57 {
            get {
                return ResourceManager.GetString("Payment_NotifySistarbanc_Error57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al interactuar con sistarbanc, el servicio no se encuentra disponible, Codigo error 9.
        /// </summary>
        public static string Payment_NotifySistarbanc_Error9 {
            get {
                return ResourceManager.GetString("Payment_NotifySistarbanc_Error9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error general comunicación con Sistarbanc. .
        /// </summary>
        public static string Payment_NotifySistarbanc_ErrorGeneral {
            get {
                return ResourceManager.GetString("Payment_NotifySistarbanc_ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE PRODUJO UN ERROR AL INTENTAR CREAR UN USUARIO EN SISTARBANC, mensaje de error {0}, id de transacción {1}, usuario {2} {3}.
        /// </summary>
        public static string Payment_NotifySistarbanc_ErrorNewUser {
            get {
                return ResourceManager.GetString("Payment_NotifySistarbanc_ErrorNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento crear el usuario ({0} {1}) en sistarbanc, id de transacción {2}.
        /// </summary>
        public static string Payment_NotifySistarbanc_NewUser {
            get {
                return ResourceManager.GetString("Payment_NotifySistarbanc_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ({0} {1}) ya esta ingresado en el sistema de sistarbanc, id de transacción {2}.
        /// </summary>
        public static string Payment_NotifySistarbanc_UserAlreadyCreated {
            get {
                return ResourceManager.GetString("Payment_NotifySistarbanc_UserAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se activo el usuario en sistarbanc. UniqueIdentifier {0} en el idBanco {1}, user {2} {3}, transaccion {4}.
        /// </summary>
        public static string Payment_NotifySistarbancUser_Ok {
            get {
                return ResourceManager.GetString("Payment_NotifySistarbancUser_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se notifico al ente por medio de pasarela Sucive, id de transacción {0}, nro factura {1}, nro pre factura {2}.
        /// </summary>
        public static string Payment_NotifySucive_Done {
            get {
                return ResourceManager.GetString("Payment_NotifySucive_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar notificar al ente por medio de Sucive, mensaje de error {0}, id de transacción {1}, nro pre factura {2}.
        /// </summary>
        public static string Payment_NotifySucive_Error {
            get {
                return ResourceManager.GetString("Payment_NotifySucive_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia el test de pago registrado para usuario {0}, servicio {1}.
        /// </summary>
        public static string PaymentTest_Loged_Init {
            get {
                return ResourceManager.GetString("PaymentTest_Loged_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuota ingresada ({0}) no es aceptada por el banco emisor del bin {1}.
        /// </summary>
        public static string Quota_Forbbiden_Bank {
            get {
                return ResourceManager.GetString("Quota_Forbbiden_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuota ingresada ({0}) no es aceptada por el tipo de tarjeta {1}.
        /// </summary>
        public static string Quota_Forbbiden_CardType {
            get {
                return ResourceManager.GetString("Quota_Forbbiden_CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuota ingresada ({0}) no es aceptada por la configuración del servicio {1}.
        /// </summary>
        public static string Quota_Forbbiden_Service {
            get {
                return ResourceManager.GetString("Quota_Forbbiden_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finaliza el proceso con errores. Id operación {0}.
        /// </summary>
        public static string Service_Apps_end_notok {
            get {
                return ResourceManager.GetString("Service_Apps_end_notok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finaliza el proceso correctamente. Id operación {0}.
        /// </summary>
        public static string Service_Apps_end_ok {
            get {
                return ResourceManager.GetString("Service_Apps_end_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia el adhesión de adhesion de un servicio de apps para usuario {0}, id app {1}, id operación {2}.
        /// </summary>
        public static string Service_Apps_init {
            get {
                return ResourceManager.GetString("Service_Apps_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio {0} tiene configuarada la LEY {1} pero el comercio {2} envio un pago con el indicador de ley {3}..
        /// </summary>
        public static string Service_DifDiscount {
            get {
                return ResourceManager.GetString("Service_DifDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia el proceso de adhesión de un servicio de carretera para usuario {0}, servicio {1}.
        /// </summary>
        public static string Service_Highway_init {
            get {
                return ResourceManager.GetString("Service_Highway_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia el proceso de adhesión de un servicio para usuario {0} ({1} {2}), servicio {3}.
        /// </summary>
        public static string Service_init {
            get {
                return ResourceManager.GetString("Service_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregar una tarjeta nueva al usuario {0}, mascara: {1}, fecha de vencimiento {2}.
        /// </summary>
        public static string ServiceApplicationUser_AddNewCard {
            get {
                return ResourceManager.GetString("ServiceApplicationUser_AddNewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El call center generó un token para restablecer la contraseña..
        /// </summary>
        public static string ServiceApplicationUser_CallCenterResetPassword {
            get {
                return ResourceManager.GetString("ServiceApplicationUser_CallCenterResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario cambió la contraseña..
        /// </summary>
        public static string ServiceApplicationUser_ChangePassword {
            get {
                return ResourceManager.GetString("ServiceApplicationUser_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario creado. Correo: {0}.
        /// </summary>
        public static string ServiceApplicationUser_CreationUser {
            get {
                return ResourceManager.GetString("ServiceApplicationUser_CreationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario editado..
        /// </summary>
        public static string ServiceApplicationUser_EditUser {
            get {
                return ResourceManager.GetString("ServiceApplicationUser_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario intentó ingresar a la aplicación. Cantidad intentos: {0}.
        /// </summary>
        public static string ServiceApplicationUser_LogInFail {
            get {
                return ResourceManager.GetString("ServiceApplicationUser_LogInFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de ingreso, nombre de usuario: {0} | contraseña: {1}.
        /// </summary>
        public static string ServiceApplicationUser_LogInFail_UserNotExist {
            get {
                return ResourceManager.GetString("ServiceApplicationUser_LogInFail_UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario reseteó la contraseña.
        /// </summary>
        public static string ServiceApplicationUser_ResetPassword {
            get {
                return ResourceManager.GetString("ServiceApplicationUser_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario modificó su contraseña a partir de un token..
        /// </summary>
        public static string ServiceApplicationUser_ResetPasswordFromTokenConfirmation {
            get {
                return ResourceManager.GetString("ServiceApplicationUser_ResetPasswordFromTokenConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la confirmación de la contraseña a partir de un token: {0}.
        /// </summary>
        public static string ServiceApplicationUser_ResetPasswordFromTokenFail {
            get {
                return ResourceManager.GetString("ServiceApplicationUser_ResetPasswordFromTokenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido bloqueado. Alcanzó la cantidad máxima de intentos de ingreso ({0}).
        /// </summary>
        public static string ServiceApplicationUser_UserLocked {
            get {
                return ResourceManager.GetString("ServiceApplicationUser_UserLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregar una tarjeta nueva al servicio asociado id {0}, id de tarjeta {1}, mascara: {2}, fecha de vencimiento {3}.
        /// </summary>
        public static string ServiceAssosiated_AddNewCard {
            get {
                return ResourceManager.GetString("ServiceAssosiated_AddNewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el servicio {0} con el usuario {1}.
        /// </summary>
        public static string ServiceAssosiated_Create {
            get {
                return ResourceManager.GetString("ServiceAssosiated_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se volvió a agregar el servicio {0} eliminado anteriormente por el usuario {1}.
        /// </summary>
        public static string ServiceAssosiated_UpdateAndActivate {
            get {
                return ResourceManager.GetString("ServiceAssosiated_UpdateAndActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistarbanc.
        /// </summary>
        public static string Sistarbanc {
            get {
                return ResourceManager.GetString("Sistarbanc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error general en comunicación con Sistarbanc. Codigo: {0}, Desc: {1}. Nro de Transación {2}.
        /// </summary>
        public static string Sistarbanc_Error_Desc {
            get {
                return ResourceManager.GetString("Sistarbanc_Error_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucive.
        /// </summary>
        public static string Sucive {
            get {
                return ResourceManager.GetString("Sucive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tc33.
        /// </summary>
        public static string Tc33 {
            get {
                return ResourceManager.GetString("Tc33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} fue bloqueado por VisaNet. Operación id {1}..
        /// </summary>
        public static string User_Blocked {
            get {
                return ResourceManager.GetString("User_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se reenvio email de confirmacion de usuario, email : {0}.
        /// </summary>
        public static string User_Confirmation_Resend {
            get {
                return ResourceManager.GetString("User_Confirmation_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} no pudo ser cargado por VisaNet. Operación id {1}..
        /// </summary>
        public static string User_ErrorLoadin {
            get {
                return ResourceManager.GetString("User_ErrorLoadin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal.
        /// </summary>
        public static string VisaNet {
            get {
                return ResourceManager.GetString("VisaNet", resourceCulture);
            }
        }
    }
}
