//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaNet.Common.Resource.EntitiesDto {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntitiesDtosStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntitiesDtosStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisaNet.Common.Resource.EntitiesDto.EntitiesDtosStrings", typeof(EntitiesDtosStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string AnonymousUserDto_Address {
            get {
                return ResourceManager.GetString("AnonymousUserDto_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string AnonymousUserDto_Email {
            get {
                return ResourceManager.GetString("AnonymousUserDto_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string AnonymousUserDto_Name {
            get {
                return ResourceManager.GetString("AnonymousUserDto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string AnonymousUserDto_Surname {
            get {
                return ResourceManager.GetString("AnonymousUserDto_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string ApplicationUserDto_Address {
            get {
                return ResourceManager.GetString("ApplicationUserDto_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave callcenter.
        /// </summary>
        public static string ApplicationUserDto_CallCenterKey {
            get {
                return ResourceManager.GetString("ApplicationUserDto_CallCenterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string ApplicationUserDto_Email {
            get {
                return ResourceManager.GetString("ApplicationUserDto_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione usuario del sitio público VISANET.
        /// </summary>
        public static string ApplicationUserDto_Id {
            get {
                return ResourceManager.GetString("ApplicationUserDto_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cédula de identidad.
        /// </summary>
        public static string ApplicationUserDto_IdentityNumber {
            get {
                return ResourceManager.GetString("ApplicationUserDto_IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Móvil.
        /// </summary>
        public static string ApplicationUserDto_MobileNumber {
            get {
                return ResourceManager.GetString("ApplicationUserDto_MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string ApplicationUserDto_Name {
            get {
                return ResourceManager.GetString("ApplicationUserDto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string ApplicationUserDto_PhoneNumber {
            get {
                return ResourceManager.GetString("ApplicationUserDto_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string ApplicationUserDto_Surname {
            get {
                return ResourceManager.GetString("ApplicationUserDto_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa.
        /// </summary>
        public static string CardDto_Active {
            get {
                return ResourceManager.GetString("CardDto_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIN.
        /// </summary>
        public static string CardDto_Bin {
            get {
                return ResourceManager.GetString("CardDto_Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string CardDto_ClientAddress {
            get {
                return ResourceManager.GetString("CardDto_ClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string CardDto_ClientEmail {
            get {
                return ResourceManager.GetString("CardDto_ClientEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cédula de identidad.
        /// </summary>
        public static string CardDto_ClientIdentityNumber {
            get {
                return ResourceManager.GetString("CardDto_ClientIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Móvil.
        /// </summary>
        public static string CardDto_ClientMobileNumber {
            get {
                return ResourceManager.GetString("CardDto_ClientMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string CardDto_ClientName {
            get {
                return ResourceManager.GetString("CardDto_ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string CardDto_ClientPhoneNumber {
            get {
                return ResourceManager.GetString("CardDto_ClientPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string CardDto_ClientSurname {
            get {
                return ResourceManager.GetString("CardDto_ClientSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminada.
        /// </summary>
        public static string CardDto_Deleted {
            get {
                return ResourceManager.GetString("CardDto_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción de la tarjeta.
        /// </summary>
        public static string CardDto_Description {
            get {
                return ResourceManager.GetString("CardDto_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de vencimiento.
        /// </summary>
        public static string CardDto_DueDate {
            get {
                return ResourceManager.GetString("CardDto_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de tarjeta.
        /// </summary>
        public static string CardDto_MaskedNumber {
            get {
                return ResourceManager.GetString("CardDto_MaskedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del titular de la tarjeta.
        /// </summary>
        public static string CardDto_Name {
            get {
                return ResourceManager.GetString("CardDto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de seguridad.
        /// </summary>
        public static string CardDto_SecurityCode {
            get {
                return ResourceManager.GetString("CardDto_SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de tarjeta.
        /// </summary>
        public static string CardDto_Type {
            get {
                return ResourceManager.GetString("CardDto_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string ContactDto_Comments {
            get {
                return ResourceManager.GetString("ContactDto_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string ContactDto_Date {
            get {
                return ResourceManager.GetString("ContactDto_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string ContactDto_Email {
            get {
                return ResourceManager.GetString("ContactDto_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string ContactDto_Message {
            get {
                return ResourceManager.GetString("ContactDto_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string ContactDto_Name {
            get {
                return ResourceManager.GetString("ContactDto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string ContactDto_PhoneNumber {
            get {
                return ResourceManager.GetString("ContactDto_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de consulta.
        /// </summary>
        public static string ContactDto_QueryType {
            get {
                return ResourceManager.GetString("ContactDto_QueryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto.
        /// </summary>
        public static string ContactDto_Subject {
            get {
                return ResourceManager.GetString("ContactDto_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string ContactDto_Surname {
            get {
                return ResourceManager.GetString("ContactDto_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario que trabajo en el contacto.
        /// </summary>
        public static string ContactDto_User_Taken {
            get {
                return ResourceManager.GetString("ContactDto_User_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llave de acceso en Cybersource (AccessKey).
        /// </summary>
        public static string CybersourceAccessKey {
            get {
                return ResourceManager.GetString("CybersourceAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identidicador de perfil en Cybersource (ProfileId).
        /// </summary>
        public static string CybersourceProfileId {
            get {
                return ResourceManager.GetString("CybersourceProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llave secreta en Cybersource (SecretKey).
        /// </summary>
        public static string CybersourceSecretKey {
            get {
                return ResourceManager.GetString("CybersourceSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuento adicional.
        /// </summary>
        public static string DiscountDto_Additional {
            get {
                return ResourceManager.GetString("DiscountDto_Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de tarjeta.
        /// </summary>
        public static string DiscountDto_CardType {
            get {
                return ResourceManager.GetString("DiscountDto_CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiqueta.
        /// </summary>
        public static string DiscountDto_DiscountLabel {
            get {
                return ResourceManager.GetString("DiscountDto_DiscountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de descuento.
        /// </summary>
        public static string DiscountDto_DiscountType {
            get {
                return ResourceManager.GetString("DiscountDto_DiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuento fijo.
        /// </summary>
        public static string DiscountDto_Fixed {
            get {
                return ResourceManager.GetString("DiscountDto_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha desde.
        /// </summary>
        public static string DiscountDto_From {
            get {
                return ResourceManager.GetString("DiscountDto_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto máximo (UI).
        /// </summary>
        public static string DiscountDto_MaximumAmount {
            get {
                return ResourceManager.GetString("DiscountDto_MaximumAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha hasta.
        /// </summary>
        public static string DiscountDto_To {
            get {
                return ResourceManager.GetString("DiscountDto_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta.
        /// </summary>
        public static string FaqDto_Answer {
            get {
                return ResourceManager.GetString("FaqDto_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden.
        /// </summary>
        public static string FaqDto_Order {
            get {
                return ResourceManager.GetString("FaqDto_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta.
        /// </summary>
        public static string FaqDto_Question {
            get {
                return ResourceManager.GetString("FaqDto_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastilla 1.
        /// </summary>
        public static string HomePageDto_HomePageItem1 {
            get {
                return ResourceManager.GetString("HomePageDto_HomePageItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastilla 2.
        /// </summary>
        public static string HomePageDto_HomePageItem2 {
            get {
                return ResourceManager.GetString("HomePageDto_HomePageItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastilla 3.
        /// </summary>
        public static string HomePageDto_HomePageItem3 {
            get {
                return ResourceManager.GetString("HomePageDto_HomePageItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string HomePageItemDto_Description {
            get {
                return ResourceManager.GetString("HomePageItemDto_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        public static string HomePageItemDto_File {
            get {
                return ResourceManager.GetString("HomePageItemDto_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabezal 1.
        /// </summary>
        public static string HomePageItemDto_Headline1 {
            get {
                return ResourceManager.GetString("HomePageItemDto_Headline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabezal 2.
        /// </summary>
        public static string HomePageItemDto_Headline2 {
            get {
                return ResourceManager.GetString("HomePageItemDto_Headline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen.
        /// </summary>
        public static string HomePageItemDto_Image {
            get {
                return ResourceManager.GetString("HomePageItemDto_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto del link.
        /// </summary>
        public static string HomePageItemDto_LinkName {
            get {
                return ResourceManager.GetString("HomePageItemDto_LinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string HomePageItemDto_LinkUrl {
            get {
                return ResourceManager.GetString("HomePageItemDto_LinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string LogDto_DateTime {
            get {
                return ResourceManager.GetString("LogDto_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de comunicación.
        /// </summary>
        public static string LogDto_LogCommunicationType {
            get {
                return ResourceManager.GetString("LogDto_LogCommunicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string LogDto_LogType {
            get {
                return ResourceManager.GetString("LogDto_LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de usuario.
        /// </summary>
        public static string LogDto_LogUserType {
            get {
                return ResourceManager.GetString("LogDto_LogUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string LogDto_Message {
            get {
                return ResourceManager.GetString("LogDto_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string LogDto_UserName {
            get {
                return ResourceManager.GetString("LogDto_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decisión.
        /// </summary>
        public static string LogPaymentCyberSourceDto_Decision {
            get {
                return ResourceManager.GetString("LogPaymentCyberSourceDto_Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string LogPaymentCyberSourceDto_Message {
            get {
                return ResourceManager.GetString("LogPaymentCyberSourceDto_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Code.
        /// </summary>
        public static string LogPaymentCyberSourceDto_ReasonCode {
            get {
                return ResourceManager.GetString("LogPaymentCyberSourceDto_ReasonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        public static string LogPaymentCyberSourceDto_ReqAmount {
            get {
                return ResourceManager.GetString("LogPaymentCyberSourceDto_ReqAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de vencimiento de tarjeta.
        /// </summary>
        public static string LogPaymentCyberSourceDto_ReqCardExpiryDate {
            get {
                return ResourceManager.GetString("LogPaymentCyberSourceDto_ReqCardExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de tarjeta.
        /// </summary>
        public static string LogPaymentCyberSourceDto_ReqCardNumber {
            get {
                return ResourceManager.GetString("LogPaymentCyberSourceDto_ReqCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        public static string LogPaymentCyberSourceDto_ReqCurrency {
            get {
                return ResourceManager.GetString("LogPaymentCyberSourceDto_ReqCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de transacción.
        /// </summary>
        public static string LogPaymentCyberSourceDto_ReqTransactionType {
            get {
                return ResourceManager.GetString("LogPaymentCyberSourceDto_ReqTransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de transacción.
        /// </summary>
        public static string LogPaymentCyberSourceDto_TransactionDateTime {
            get {
                return ResourceManager.GetString("LogPaymentCyberSourceDto_TransactionDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID de transacción.
        /// </summary>
        public static string LogPaymentCyberSourceDto_TransactionId {
            get {
                return ResourceManager.GetString("LogPaymentCyberSourceDto_TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string MembershipUserDto_Active {
            get {
                return ResourceManager.GetString("MembershipUserDto_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallos de Inicio de Sesión.
        /// </summary>
        public static string MembershipUserDto_FailLogInCount {
            get {
                return ResourceManager.GetString("MembershipUserDto_FailLogInCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        public static string Notifications_Category {
            get {
                return ResourceManager.GetString("Notifications_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string Notifications_Comments {
            get {
                return ResourceManager.GetString("Notifications_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Notifications_DateTime {
            get {
                return ResourceManager.GetString("Notifications_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Notifications_Description {
            get {
                return ResourceManager.GetString("Notifications_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string Notifications_Detail {
            get {
                return ResourceManager.GetString("Notifications_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severidad.
        /// </summary>
        public static string Notifications_Level {
            get {
                return ResourceManager.GetString("Notifications_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuelto.
        /// </summary>
        public static string Notifications_Resolved {
            get {
                return ResourceManager.GetString("Notifications_Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código banco Banred.
        /// </summary>
        public static string ParametersDto_Banred {
            get {
                return ResourceManager.GetString("ParametersDto_Banred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail de contacto.
        /// </summary>
        public static string ParametersDto_Contact {
            get {
                return ResourceManager.GetString("ParametersDto_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Cybersource.
        /// </summary>
        public static string ParametersDto_Cybersource {
            get {
                return ResourceManager.GetString("ParametersDto_Cybersource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail de notificación de errores.
        /// </summary>
        public static string ParametersDto_ErrorNotification {
            get {
                return ResourceManager.GetString("ParametersDto_ErrorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Geocom.
        /// </summary>
        public static string ParametersDto_GeocomCode {
            get {
                return ResourceManager.GetString("ParametersDto_GeocomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de intentos fallidos previo al bloqueo de cuenta.
        /// </summary>
        public static string ParametersDto_LoginNumberOfTries {
            get {
                return ResourceManager.GetString("ParametersDto_LoginNumberOfTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail de envío de mails.
        /// </summary>
        public static string ParametersDto_SendingEmail {
            get {
                return ResourceManager.GetString("ParametersDto_SendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código banco Sistarbanc.
        /// </summary>
        public static string ParametersDto_Sistarbanc {
            get {
                return ResourceManager.GetString("ParametersDto_Sistarbanc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código banco Sistarbanc Brou.
        /// </summary>
        public static string ParametersDto_SistarbancBrou {
            get {
                return ResourceManager.GetString("ParametersDto_SistarbancBrou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Sucive.
        /// </summary>
        public static string ParametersDto_Sucive {
            get {
                return ResourceManager.GetString("ParametersDto_Sucive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto total a CyberSource.
        /// </summary>
        public static string PaymentDto_AmountToCS {
            get {
                return ResourceManager.GetString("PaymentDto_AmountToCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto factura.
        /// </summary>
        public static string PaymentDto_BillAmount {
            get {
                return ResourceManager.GetString("PaymentDto_BillAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda factura.
        /// </summary>
        public static string PaymentDto_BillCurrency {
            get {
                return ResourceManager.GetString("PaymentDto_BillCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto del descuento factura.
        /// </summary>
        public static string PaymentDto_BillDiscountAmount {
            get {
                return ResourceManager.GetString("PaymentDto_BillDiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuento aplicado factura.
        /// </summary>
        public static string PaymentDto_BillDiscountApplied {
            get {
                return ResourceManager.GetString("PaymentDto_BillDiscountApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de vencimiento de factura.
        /// </summary>
        public static string PaymentDto_BillExpirationDate {
            get {
                return ResourceManager.GetString("PaymentDto_BillExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de factura.
        /// </summary>
        public static string PaymentDto_BillExternalId {
            get {
                return ResourceManager.GetString("PaymentDto_BillExternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumidor final.
        /// </summary>
        public static string PaymentDto_BillFinalConsumer {
            get {
                return ResourceManager.GetString("PaymentDto_BillFinalConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto gravado factura.
        /// </summary>
        public static string PaymentDto_BillTaxedAmount {
            get {
                return ResourceManager.GetString("PaymentDto_BillTaxedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIN.
        /// </summary>
        public static string PaymentDto_CardBin {
            get {
                return ResourceManager.GetString("PaymentDto_CardBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de vencimiento de tarjeta.
        /// </summary>
        public static string PaymentDto_CardDueDate {
            get {
                return ResourceManager.GetString("PaymentDto_CardDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de tarjeta.
        /// </summary>
        public static string PaymentDto_CardMaskedNumber {
            get {
                return ResourceManager.GetString("PaymentDto_CardMaskedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de tarjeta.
        /// </summary>
        public static string PaymentDto_CardType {
            get {
                return ResourceManager.GetString("PaymentDto_CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string PaymentDto_ClientAddress {
            get {
                return ResourceManager.GetString("PaymentDto_ClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string PaymentDto_ClientEmail {
            get {
                return ResourceManager.GetString("PaymentDto_ClientEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string PaymentDto_ClientName {
            get {
                return ResourceManager.GetString("PaymentDto_ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string PaymentDto_ClientSurname {
            get {
                return ResourceManager.GetString("PaymentDto_ClientSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de aprobación de CyberSource.
        /// </summary>
        public static string PaymentDto_CSAuthCode {
            get {
                return ResourceManager.GetString("PaymentDto_CSAuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha aprobación de CyberSource.
        /// </summary>
        public static string PaymentDto_CSAuthTime {
            get {
                return ResourceManager.GetString("PaymentDto_CSAuthTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda de pago a CyberSource.
        /// </summary>
        public static string PaymentDto_CSRequestCurrency {
            get {
                return ResourceManager.GetString("PaymentDto_CSRequestCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Transacción en CyberSource.
        /// </summary>
        public static string PaymentDto_CSTransactionIdentifier {
            get {
                return ResourceManager.GetString("PaymentDto_CSTransactionIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string PaymentDto_Date {
            get {
                return ResourceManager.GetString("PaymentDto_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string PaymentDto_Description {
            get {
                return ResourceManager.GetString("PaymentDto_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto del descuento del pago.
        /// </summary>
        public static string PaymentDto_Discount {
            get {
                return ResourceManager.GetString("PaymentDto_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasarela de pago.
        /// </summary>
        public static string PaymentDto_Gateway {
            get {
                return ResourceManager.GetString("PaymentDto_Gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Transacción en pasarela.
        /// </summary>
        public static string PaymentDto_GatewayTransactionId {
            get {
                return ResourceManager.GetString("PaymentDto_GatewayTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción del pago.
        /// </summary>
        public static string PaymentDto_PaymentDescription {
            get {
                return ResourceManager.GetString("PaymentDto_PaymentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string PaymentDto_PaymentStatus {
            get {
                return ResourceManager.GetString("PaymentDto_PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string PaymentDto_PaymentType {
            get {
                return ResourceManager.GetString("PaymentDto_PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de referencia.
        /// </summary>
        public static string PaymentDto_ReferenceNumber {
            get {
                return ResourceManager.GetString("PaymentDto_ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Números de referencia.
        /// </summary>
        public static string PaymentDto_ReferenceNumbers {
            get {
                return ResourceManager.GetString("PaymentDto_ReferenceNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción del servicio.
        /// </summary>
        public static string PaymentDto_ServiceAssociatedDescription {
            get {
                return ResourceManager.GetString("PaymentDto_ServiceAssociatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría de servicios.
        /// </summary>
        public static string PaymentDto_ServiceCategoryName {
            get {
                return ResourceManager.GetString("PaymentDto_ServiceCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio a pagar.
        /// </summary>
        public static string PaymentDto_ServiceId {
            get {
                return ResourceManager.GetString("PaymentDto_ServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        public static string PaymentDto_ServiceName {
            get {
                return ResourceManager.GetString("PaymentDto_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de pre-factura Sucive.
        /// </summary>
        public static string PaymentDto_SucivePreBillNumber {
            get {
                return ResourceManager.GetString("PaymentDto_SucivePreBillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto gravado del pago.
        /// </summary>
        public static string PaymentDto_TaxedAmount {
            get {
                return ResourceManager.GetString("PaymentDto_TaxedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto total del pago.
        /// </summary>
        public static string PaymentDto_TotalAmount {
            get {
                return ResourceManager.GetString("PaymentDto_TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de transacción.
        /// </summary>
        public static string PaymentDto_TransactionNumber {
            get {
                return ResourceManager.GetString("PaymentDto_TransactionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID de pasarela de pago.
        /// </summary>
        public static string PaymentDto_UniqueIdentifier {
            get {
                return ResourceManager.GetString("PaymentDto_UniqueIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string RoleDto_Name {
            get {
                return ResourceManager.GetString("RoleDto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string RoleModel_Name {
            get {
                return ResourceManager.GetString("RoleModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador de servicio en cybersource (MerchantId).
        /// </summary>
        public static string Service_CybersourceId {
            get {
                return ResourceManager.GetString("Service_CybersourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago programado.
        /// </summary>
        public static string ServiceAssociatedDto_AutomaticPayment {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_AutomaticPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIN.
        /// </summary>
        public static string ServiceAssociatedDto_CardBin {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_CardBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de vencimiento de tarjeta.
        /// </summary>
        public static string ServiceAssociatedDto_CardDueDate {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_CardDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de tarjeta.
        /// </summary>
        public static string ServiceAssociatedDto_CardMaskedNumber {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_CardMaskedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de tarjeta.
        /// </summary>
        public static string ServiceAssociatedDto_CardType {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string ServiceAssociatedDto_ClientAddress {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_ClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string ServiceAssociatedDto_ClientEmail {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_ClientEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cédula de identidad.
        /// </summary>
        public static string ServiceAssociatedDto_ClientIdentityNumber {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_ClientIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Móvil.
        /// </summary>
        public static string ServiceAssociatedDto_ClientMobileNumber {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_ClientMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string ServiceAssociatedDto_ClientName {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string ServiceAssociatedDto_ClientPhoneNumber {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_ClientPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string ServiceAssociatedDto_ClientSurname {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_ClientSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string ServiceAssociatedDto_Description {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string ServiceAssociatedDto_Enabled {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de referencia.
        /// </summary>
        public static string ServiceAssociatedDto_ReferenceNumber {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría de servicios.
        /// </summary>
        public static string ServiceAssociatedDto_ServiceCategoryName {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_ServiceCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        public static string ServiceAssociatedDto_ServiceName {
            get {
                return ResourceManager.GetString("ServiceAssociatedDto_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string SubscriberDto_Email {
            get {
                return ResourceManager.GetString("SubscriberDto_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string SubscriberDto_Name {
            get {
                return ResourceManager.GetString("SubscriberDto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string SubscriberDto_Surname {
            get {
                return ResourceManager.GetString("SubscriberDto_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitado.
        /// </summary>
        public static string SystemUserDto_Enabled {
            get {
                return ResourceManager.GetString("SystemUserDto_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Usuario (LDAP).
        /// </summary>
        public static string SystemUserDto_LDAPUserName {
            get {
                return ResourceManager.GetString("SystemUserDto_LDAPUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string SystemUserDto_Roles {
            get {
                return ResourceManager.GetString("SystemUserDto_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de usuario.
        /// </summary>
        public static string SystemUserDto_SystemUserType {
            get {
                return ResourceManager.GetString("SystemUserDto_SystemUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Creación.
        /// </summary>
        public static string Tc33Dto_CreationDate {
            get {
                return ResourceManager.GetString("Tc33Dto_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario de Creación.
        /// </summary>
        public static string Tc33Dto_CreationUser {
            get {
                return ResourceManager.GetString("Tc33Dto_CreationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Archivo de Entrada.
        /// </summary>
        public static string Tc33Dto_InputFileName {
            get {
                return ResourceManager.GetString("Tc33Dto_InputFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Archivo de Salida.
        /// </summary>
        public static string Tc33Dto_OutputFileName {
            get {
                return ResourceManager.GetString("Tc33Dto_OutputFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Tc33Dto_State {
            get {
                return ResourceManager.GetString("Tc33Dto_State", resourceCulture);
            }
        }
    }
}
