//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "WsAltasBajasSoapBinding", Namespace = "https://spf.sistarbanc.com.uy/spfws/services/WsAltasBajas")]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(Resultado))]
public partial class WsAltasBajasImpService : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback bajaClienteOperationCompleted;

    private System.Threading.SendOrPostCallback altaPerfilOperationCompleted;

    private System.Threading.SendOrPostCallback bajaPerfilOperationCompleted;

    private System.Threading.SendOrPostCallback altaClienteOperationCompleted;

    private System.Threading.SendOrPostCallback altaCliente1OperationCompleted;

    /// <remarks/>
    public WsAltasBajasImpService()
    {
        this.Url = "https://192.168.141.190/spfws/services/WsAltasBajas";
    }

    /// <remarks/>
    public event bajaClienteCompletedEventHandler bajaClienteCompleted;

    /// <remarks/>
    public event altaPerfilCompletedEventHandler altaPerfilCompleted;

    /// <remarks/>
    public event bajaPerfilCompletedEventHandler bajaPerfilCompleted;

    /// <remarks/>
    public event altaClienteCompletedEventHandler altaClienteCompleted;

    /// <remarks/>
    public event altaCliente1CompletedEventHandler altaCliente1Completed;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "https://spf.sistarbanc.com.uy/spfws/services/WsAltasBajas", ResponseNamespace = "https://spf.sistarbanc.com.uy/spfws/services/WsAltasBajas")]
    [return: System.Xml.Serialization.SoapElementAttribute("bajaClienteReturn")]
    public ResultadoAltasBajas bajaCliente(string banco, string idClienteBanco, string firma)
    {
        object[] results = this.Invoke("bajaCliente", new object[] {
                    banco,
                    idClienteBanco,
                    firma});
        return ((ResultadoAltasBajas)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginbajaCliente(string banco, string idClienteBanco, string firma, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("bajaCliente", new object[] {
                    banco,
                    idClienteBanco,
                    firma}, callback, asyncState);
    }

    /// <remarks/>
    public ResultadoAltasBajas EndbajaCliente(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResultadoAltasBajas)(results[0]));
    }

    /// <remarks/>
    public void bajaClienteAsync(string banco, string idClienteBanco, string firma)
    {
        this.bajaClienteAsync(banco, idClienteBanco, firma, null);
    }

    /// <remarks/>
    public void bajaClienteAsync(string banco, string idClienteBanco, string firma, object userState)
    {
        if ((this.bajaClienteOperationCompleted == null))
        {
            this.bajaClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbajaClienteOperationCompleted);
        }
        this.InvokeAsync("bajaCliente", new object[] {
                    banco,
                    idClienteBanco,
                    firma}, this.bajaClienteOperationCompleted, userState);
    }

    private void OnbajaClienteOperationCompleted(object arg)
    {
        if ((this.bajaClienteCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.bajaClienteCompleted(this, new bajaClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "https://spf.sistarbanc.com.uy/spfws/services/WsAltasBajas", ResponseNamespace = "https://spf.sistarbanc.com.uy/spfws/services/WsAltasBajas")]
    [return: System.Xml.Serialization.SoapElementAttribute("altaPerfilReturn")]
    public ResultadoAltasBajas altaPerfil(string banco, string idClienteBanco, string idOrganismo, string tipoServicio, string[] idServicio, string otrosDatos, string firma)
    {
        object[] results = this.Invoke("altaPerfil", new object[] {
                    banco,
                    idClienteBanco,
                    idOrganismo,
                    tipoServicio,
                    idServicio,
                    otrosDatos,
                    firma});
        return ((ResultadoAltasBajas)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginaltaPerfil(string banco, string idClienteBanco, string idOrganismo, string tipoServicio, string[] idServicio, string otrosDatos, string firma, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("altaPerfil", new object[] {
                    banco,
                    idClienteBanco,
                    idOrganismo,
                    tipoServicio,
                    idServicio,
                    otrosDatos,
                    firma}, callback, asyncState);
    }

    /// <remarks/>
    public ResultadoAltasBajas EndaltaPerfil(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResultadoAltasBajas)(results[0]));
    }

    /// <remarks/>
    public void altaPerfilAsync(string banco, string idClienteBanco, string idOrganismo, string tipoServicio, string[] idServicio, string otrosDatos, string firma)
    {
        this.altaPerfilAsync(banco, idClienteBanco, idOrganismo, tipoServicio, idServicio, otrosDatos, firma, null);
    }

    /// <remarks/>
    public void altaPerfilAsync(string banco, string idClienteBanco, string idOrganismo, string tipoServicio, string[] idServicio, string otrosDatos, string firma, object userState)
    {
        if ((this.altaPerfilOperationCompleted == null))
        {
            this.altaPerfilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaltaPerfilOperationCompleted);
        }
        this.InvokeAsync("altaPerfil", new object[] {
                    banco,
                    idClienteBanco,
                    idOrganismo,
                    tipoServicio,
                    idServicio,
                    otrosDatos,
                    firma}, this.altaPerfilOperationCompleted, userState);
    }

    private void OnaltaPerfilOperationCompleted(object arg)
    {
        if ((this.altaPerfilCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.altaPerfilCompleted(this, new altaPerfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "https://spf.sistarbanc.com.uy/spfws/services/WsAltasBajas", ResponseNamespace = "https://spf.sistarbanc.com.uy/spfws/services/WsAltasBajas")]
    [return: System.Xml.Serialization.SoapElementAttribute("bajaPerfilReturn")]
    public ResultadoAltasBajas bajaPerfil(string banco, string idClienteBanco, string idOrganismo, string tipoServicio, string[] idServicio, string firma)
    {
        object[] results = this.Invoke("bajaPerfil", new object[] {
                    banco,
                    idClienteBanco,
                    idOrganismo,
                    tipoServicio,
                    idServicio,
                    firma});
        return ((ResultadoAltasBajas)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginbajaPerfil(string banco, string idClienteBanco, string idOrganismo, string tipoServicio, string[] idServicio, string firma, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("bajaPerfil", new object[] {
                    banco,
                    idClienteBanco,
                    idOrganismo,
                    tipoServicio,
                    idServicio,
                    firma}, callback, asyncState);
    }

    /// <remarks/>
    public ResultadoAltasBajas EndbajaPerfil(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResultadoAltasBajas)(results[0]));
    }

    /// <remarks/>
    public void bajaPerfilAsync(string banco, string idClienteBanco, string idOrganismo, string tipoServicio, string[] idServicio, string firma)
    {
        this.bajaPerfilAsync(banco, idClienteBanco, idOrganismo, tipoServicio, idServicio, firma, null);
    }

    /// <remarks/>
    public void bajaPerfilAsync(string banco, string idClienteBanco, string idOrganismo, string tipoServicio, string[] idServicio, string firma, object userState)
    {
        if ((this.bajaPerfilOperationCompleted == null))
        {
            this.bajaPerfilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbajaPerfilOperationCompleted);
        }
        this.InvokeAsync("bajaPerfil", new object[] {
                    banco,
                    idClienteBanco,
                    idOrganismo,
                    tipoServicio,
                    idServicio,
                    firma}, this.bajaPerfilOperationCompleted, userState);
    }

    private void OnbajaPerfilOperationCompleted(object arg)
    {
        if ((this.bajaPerfilCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.bajaPerfilCompleted(this, new bajaPerfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "https://spf.sistarbanc.com.uy/spfws/services/WsAltasBajas", ResponseNamespace = "https://spf.sistarbanc.com.uy/spfws/services/WsAltasBajas")]
    [return: System.Xml.Serialization.SoapElementAttribute("altaClienteReturn")]
    public ResultadoAltasBajas altaCliente(string banco, string idClienteBanco, string nombre, string apellido, string firma)
    {
        object[] results = this.Invoke("altaCliente", new object[] {
                    banco,
                    idClienteBanco,
                    nombre,
                    apellido,
                    firma});
        return ((ResultadoAltasBajas)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginaltaCliente(string banco, string idClienteBanco, string nombre, string apellido, string firma, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("altaCliente", new object[] {
                    banco,
                    idClienteBanco,
                    nombre,
                    apellido,
                    firma}, callback, asyncState);
    }

    /// <remarks/>
    public ResultadoAltasBajas EndaltaCliente(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResultadoAltasBajas)(results[0]));
    }

    /// <remarks/>
    public void altaClienteAsync(string banco, string idClienteBanco, string nombre, string apellido, string firma)
    {
        this.altaClienteAsync(banco, idClienteBanco, nombre, apellido, firma, null);
    }

    /// <remarks/>
    public void altaClienteAsync(string banco, string idClienteBanco, string nombre, string apellido, string firma, object userState)
    {
        if ((this.altaClienteOperationCompleted == null))
        {
            this.altaClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaltaClienteOperationCompleted);
        }
        this.InvokeAsync("altaCliente", new object[] {
                    banco,
                    idClienteBanco,
                    nombre,
                    apellido,
                    firma}, this.altaClienteOperationCompleted, userState);
    }

    private void OnaltaClienteOperationCompleted(object arg)
    {
        if ((this.altaClienteCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.altaClienteCompleted(this, new altaClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.WebMethodAttribute(MessageName = "altaCliente1")]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "https://spf.sistarbanc.com.uy/spfws/services/WsAltasBajas", ResponseNamespace = "https://spf.sistarbanc.com.uy/spfws/services/WsAltasBajas")]
    [return: System.Xml.Serialization.SoapElementAttribute("altaClienteReturn")]
    public ResultadoAltasBajas altaCliente(string banco, string idClienteBanco, string nombre, string apellido, string usuario, string password, string firma)
    {
        object[] results = this.Invoke("altaCliente1", new object[] {
                    banco,
                    idClienteBanco,
                    nombre,
                    apellido,
                    usuario,
                    password,
                    firma});
        return ((ResultadoAltasBajas)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginaltaCliente1(string banco, string idClienteBanco, string nombre, string apellido, string usuario, string password, string firma, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("altaCliente1", new object[] {
                    banco,
                    idClienteBanco,
                    nombre,
                    apellido,
                    usuario,
                    password,
                    firma}, callback, asyncState);
    }

    /// <remarks/>
    public ResultadoAltasBajas EndaltaCliente1(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResultadoAltasBajas)(results[0]));
    }

    /// <remarks/>
    public void altaCliente1Async(string banco, string idClienteBanco, string nombre, string apellido, string usuario, string password, string firma)
    {
        this.altaCliente1Async(banco, idClienteBanco, nombre, apellido, usuario, password, firma, null);
    }

    /// <remarks/>
    public void altaCliente1Async(string banco, string idClienteBanco, string nombre, string apellido, string usuario, string password, string firma, object userState)
    {
        if ((this.altaCliente1OperationCompleted == null))
        {
            this.altaCliente1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnaltaCliente1OperationCompleted);
        }
        this.InvokeAsync("altaCliente1", new object[] {
                    banco,
                    idClienteBanco,
                    nombre,
                    apellido,
                    usuario,
                    password,
                    firma}, this.altaCliente1OperationCompleted, userState);
    }

    private void OnaltaCliente1OperationCompleted(object arg)
    {
        if ((this.altaCliente1Completed != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.altaCliente1Completed(this, new altaCliente1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:WsAltasBajasImp")]
public partial class ResultadoAltasBajas : Resultado
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void bajaClienteCompletedEventHandler(object sender, bajaClienteCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class bajaClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal bajaClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public ResultadoAltasBajas Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((ResultadoAltasBajas)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void altaPerfilCompletedEventHandler(object sender, altaPerfilCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class altaPerfilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal altaPerfilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public ResultadoAltasBajas Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((ResultadoAltasBajas)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void bajaPerfilCompletedEventHandler(object sender, bajaPerfilCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class bajaPerfilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal bajaPerfilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public ResultadoAltasBajas Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((ResultadoAltasBajas)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void altaClienteCompletedEventHandler(object sender, altaClienteCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class altaClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal altaClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public ResultadoAltasBajas Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((ResultadoAltasBajas)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void altaCliente1CompletedEventHandler(object sender, altaCliente1CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class altaCliente1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal altaCliente1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public ResultadoAltasBajas Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((ResultadoAltasBajas)(this.results[0]));
        }
    }
}
